In [1]:
import pandas as pd
med_2023=pd.read_excel("E:\Python\SESSION-1\A2.RAW_DATA\MED_STORE_2022.xlsx",sheet_name="MED_AUS_DATA")
med_2023

CUSTOMER_ID    Company        CARD_REG_DATE CARD_ACTIVE  \
0      1000032547      MED +  2006-09-12 00:00:00           Y   
1      1000032548  DR.REDDYS  2006-09-12 00:00:00           Y   
2      1000032549   RELEGARE  2006-09-12 00:00:00           Y   
3      1000032550        GSK  2006-09-12 00:00:00           Y   
4      1000032551        GSK  2006-09-12 00:00:00           Y   
...           ...        ...                  ...         ...   
5107   1000037830   RELEGARE  2008-05-06 00:00:00           Y   
5108   1000037831     APPOLO  2008-05-06 00:00:00           Y   
5109   1000037832        GSK  2008-05-06 00:00:00           Y   
5110   1000037833      MED +  2008-05-06 00:00:00           Y   
5111   1000037834    RANBAXY  2008-05-06 00:00:00           Y   

            FIRST_USE_DTE  firstSTOR TITLE  GENDER  max spent        DOB  ...  \
0     2007-05-12 00:00:00       2587  Mrs.  Female      56.31 1984-09-15  ...   
1     2007-03-12 00:00:00       4341   Ms.  Female     598.95 1974-07-15  ...   
2     2007-02-12 00:00:00       1090  Mrs.  Female       1.56 1959-04-01  ...   
3     2007-03-12 00:00:00       3179   Mr.    Male     115.76 1978-05-16  ...   
4     2007-05-12 00:00:00       3135   Mr.    Male     305.90 1978-12-16  ...   
...                   ...        ...   ...     ...        ...        ...  ...   
5107  2009-05-02 00:00:00       3381   Mr.    Male     198.36 1935-11-23  ...   
5108  2008-10-06 00:00:00       3244  Mrs.  Female      28.09 1956-08-27  ...   
5109  2009-05-04 00:00:00       3381  Mrs.  Female     653.10 1982-05-13  ...   
5110  2009-06-10 00:00:00       3130   Ms.  Female     228.55 1960-01-14  ...   
5111  2009-05-04 00:00:00       3363  Mrs.  Female      26.35 1971-12-22  ...   

     CUST_STAT  Avgsize spent   CARD_STAT  RGSTN_TYPE_IND NO_OF_TRIPS  \
0       Active          17.34  Registered          Online           4   
1       Active          29.32  Registered          Online          17   
2       Active           1.56  Registered          Online           1   
3       Active          80.49  Registered          Online           2   
4       Active          24.09  Registered          Online          12   
...        ...            ...         ...             ...         ...   
5107    Active          66.12  Registered          Online           3   
5108    Active          28.09  Registered          Online           1   
5109    Active          94.77  Registered           Phone           9   
5110    Active          38.09  Registered          Online           6   
5111    Active          26.35  Registered      Instore/RF           1   

               TOWN EMAIL_IND CONTACT_PREF  Average_Qty_PER_ACC Spent amount  
0           Kyabram         Y        Email                 2.75        69.37  
1     Hawthorn East         Y        Email                 7.29       498.50  
2           Revesby         Y        Email                 2.00         1.56  
3      Willow Grove         Y        Email                26.00       160.98  
4         mona vale         Y        Email                 6.33       289.10  
...             ...       ...          ...                  ...          ...  
5107       Kyvalley         N          NaN                21.33       198.36  
5108      frankston         Y        Email                10.00        28.09  
5109        KYABRAM         N          NaN                27.44       852.98  
5110       Mulgrave         Y        Email                 8.00       228.55  
5111        WODONGA         Y          NaN                 7.00        26.35  

[5112 rows x 24 columns]

In [2]:
import numpy as np


In [3]:
income=np.array([120,140,150,190,145])

In [4]:
income

array([120, 140, 150, 190, 145])

In [5]:
income1=[120,140,150,190,145]

# Difference between list and array

In [6]:
expense =income *0.4
expense

array([48., 56., 60., 76., 58.])

In [7]:
expense1=income1 * 0.4

TypeError: can't multiply sequence by non-int of type 'float'

In [8]:
savings=income-expense
savings

array([ 72.,  84.,  90., 114.,  87.])

In [9]:
x1=np.array([23,34,31,27,'a'])
x1

array(['23', '34', '31', '27', 'a'], dtype='<U11')

In [10]:
x2=[23,23,45,64,61,'a','b']
x2

[23, 23, 45, 64, 61, 'a', 'b']

# N-dimensional Arrays

In [11]:
a=np.array([12,31,43],[43,55,81])
a

TypeError: Field elements must be 2- or 3-tuples, got '43'

In [12]:
a=np.array([[12,31,43],[43,55,81]])
a

array([[12, 31, 43],
       [43, 55, 81]])

In [13]:
b=np.array([[23,34],[41,23],[54,56]])
b

array([[23, 34],
       [41, 23],
       [54, 56]])

In [14]:
a=np.array([[12,31,43],[43,55,]])
a

C:\Users\DELL\AppData\Local\Temp\ipykernel_19636\1235501030.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  a=np.array([[12,31,43],[43,55,]])


array([list([12, 31, 43]), list([43, 55])], dtype=object)

# How to get the size, shape and dimension of arrays

In [15]:
a=np.array([[12,31,43],[43,55,81]])
a

array([[12, 31, 43],
       [43, 55, 81]])

In [17]:
b=np.array([[23,34],[41,23],[54,56]])
b

array([[23, 34],
       [41, 23],
       [54, 56]])

In [16]:
a.shape

(2, 3)

In [18]:
b.shape

(3, 2)

In [19]:
a.size

6

In [20]:
a.ndim

2

In [21]:
c=np.array([[[23,32,21],[34,45,41],[45,67,78]]])
c

array([[[23, 32, 21],
        [34, 45, 41],
        [45, 67, 78]]])

In [22]:
c.shape

(1, 3, 3)

In [23]:
c.size

9

In [24]:
c.ndim

3

# Real time use of arrays

In [25]:
med_2023

CUSTOMER_ID    Company        CARD_REG_DATE CARD_ACTIVE  \
0      1000032547      MED +  2006-09-12 00:00:00           Y   
1      1000032548  DR.REDDYS  2006-09-12 00:00:00           Y   
2      1000032549   RELEGARE  2006-09-12 00:00:00           Y   
3      1000032550        GSK  2006-09-12 00:00:00           Y   
4      1000032551        GSK  2006-09-12 00:00:00           Y   
...           ...        ...                  ...         ...   
5107   1000037830   RELEGARE  2008-05-06 00:00:00           Y   
5108   1000037831     APPOLO  2008-05-06 00:00:00           Y   
5109   1000037832        GSK  2008-05-06 00:00:00           Y   
5110   1000037833      MED +  2008-05-06 00:00:00           Y   
5111   1000037834    RANBAXY  2008-05-06 00:00:00           Y   

            FIRST_USE_DTE  firstSTOR TITLE  GENDER  max spent        DOB  ...  \
0     2007-05-12 00:00:00       2587  Mrs.  Female      56.31 1984-09-15  ...   
1     2007-03-12 00:00:00       4341   Ms.  Female     598.95 1974-07-15  ...   
2     2007-02-12 00:00:00       1090  Mrs.  Female       1.56 1959-04-01  ...   
3     2007-03-12 00:00:00       3179   Mr.    Male     115.76 1978-05-16  ...   
4     2007-05-12 00:00:00       3135   Mr.    Male     305.90 1978-12-16  ...   
...                   ...        ...   ...     ...        ...        ...  ...   
5107  2009-05-02 00:00:00       3381   Mr.    Male     198.36 1935-11-23  ...   
5108  2008-10-06 00:00:00       3244  Mrs.  Female      28.09 1956-08-27  ...   
5109  2009-05-04 00:00:00       3381  Mrs.  Female     653.10 1982-05-13  ...   
5110  2009-06-10 00:00:00       3130   Ms.  Female     228.55 1960-01-14  ...   
5111  2009-05-04 00:00:00       3363  Mrs.  Female      26.35 1971-12-22  ...   

     CUST_STAT  Avgsize spent   CARD_STAT  RGSTN_TYPE_IND NO_OF_TRIPS  \
0       Active          17.34  Registered          Online           4   
1       Active          29.32  Registered          Online          17   
2       Active           1.56  Registered          Online           1   
3       Active          80.49  Registered          Online           2   
4       Active          24.09  Registered          Online          12   
...        ...            ...         ...             ...         ...   
5107    Active          66.12  Registered          Online           3   
5108    Active          28.09  Registered          Online           1   
5109    Active          94.77  Registered           Phone           9   
5110    Active          38.09  Registered          Online           6   
5111    Active          26.35  Registered      Instore/RF           1   

               TOWN EMAIL_IND CONTACT_PREF  Average_Qty_PER_ACC Spent amount  
0           Kyabram         Y        Email                 2.75        69.37  
1     Hawthorn East         Y        Email                 7.29       498.50  
2           Revesby         Y        Email                 2.00         1.56  
3      Willow Grove         Y        Email                26.00       160.98  
4         mona vale         Y        Email                 6.33       289.10  
...             ...       ...          ...                  ...          ...  
5107       Kyvalley         N          NaN                21.33       198.36  
5108      frankston         Y        Email                10.00        28.09  
5109        KYABRAM         N          NaN                27.44       852.98  
5110       Mulgrave         Y        Email                 8.00       228.55  
5111        WODONGA         Y          NaN                 7.00        26.35  

[5112 rows x 24 columns]

In [26]:
med_2023.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5112 entries, 0 to 5111
Data columns (total 24 columns):
 #   Column               Non-Null Count  Dtype         
---  ------               --------------  -----         
 0   CUSTOMER_ID          5112 non-null   int64         
 1   Company              5112 non-null   object        
 2   CARD_REG_DATE        5112 non-null   object        
 3   CARD_ACTIVE          5112 non-null   object        
 4   FIRST_USE_DTE        5112 non-null   object        
 5   firstSTOR            5112 non-null   int64         
 6   TITLE                5112 non-null   object        
 7   GENDER               5112 non-null   object        
 8   max spent            5097 non-null   float64       
 9   DOB                  5112 non-null   datetime64[ns]
 10  FTD                  5112 non-null   object        
 11  Age                  5112 non-null   int64         
 12  STATE_CODE           5112 non-null   object        
 13  POST_CODE            5112 non-nul

In [27]:
age_var=np.array(med_2023['Age'])
age_var

array([29, 39, 54, ..., 31, 53, 41], dtype=int64)

In [28]:
type(age_var)

numpy.ndarray

In [29]:
age_var.size

5112

# Indexing in 1D arrays

In [30]:
age_var[-1]

41

In [31]:
age_var[0]

29

In [32]:
age_var[-15:]

array([78, 31, 61, 64, 42, 65, 74, 49, 25, 31, 77, 57, 31, 53, 41],
      dtype=int64)

In [33]:
age_var[:]

array([29, 39, 54, ..., 31, 53, 41], dtype=int64)

In [34]:
age_var[10:2]

array([], dtype=int64)

In [35]:
age_var[3,5,7]

IndexError: too many indices for array: array is 1-dimensional, but 3 were indexed

In [36]:
age_var[[3,5,7]]

array([35, 26, 26], dtype=int64)

# Indexing in 2-D arrays

In [37]:
two_vars=np.array(med_2023[['Age','NO_OF_TRIPS']])
two_vars

array([[29,  4],
       [39, 17],
       [54,  1],
       ...,
       [31,  9],
       [53,  6],
       [41,  1]], dtype=int64)

In [38]:
two_vars.shape

(5112, 2)

In [39]:
two_vars.ndim

2

In [40]:
two_vars[0,0]

29

In [41]:
two_vars[0,1]

4

In [42]:
two_vars[2,1]

1

In [43]:
two_vars[-1]

array([41,  1], dtype=int64)

In [44]:
two_vars

array([[29,  4],
       [39, 17],
       [54,  1],
       ...,
       [31,  9],
       [53,  6],
       [41,  1]], dtype=int64)

In [45]:
two_vars[0:2,0]

array([29, 39], dtype=int64)

In [46]:
two_vars[-2,0:2]

array([53,  6], dtype=int64)

In [47]:
two_vars[-2,0:3]

array([53,  6], dtype=int64)

In [48]:
two_vars[-2,2]

IndexError: index 2 is out of bounds for axis 1 with size 2

# Boolean Indexing

In [49]:
age_var

array([29, 39, 54, ..., 31, 53, 41], dtype=int64)

In [50]:
#Suppose if someone asked us to get all the customers with age < 40

condition= age_var <40
condition

array([ True,  True, False, ...,  True, False, False])

In [51]:
new_array=age_var[condition]
new_array

array([29, 39, 35, ..., 25, 31, 31], dtype=int64)

In [52]:
print(age_var.size)
print(new_array.size)

5112
1354


In [53]:
new_array1=age_var[condition==False]
new_array1

array([54, 55, 61, ..., 57, 53, 41], dtype=int64)

In [54]:
print(new_array1.shape)

(3758,)


In [55]:
new_array1.size

3758

# Use of where statement in arrays

In [ ]:
#Where statement can be used to update our original arrays depending on our conditions
#Parameters to be passed in where conditions are :-
#1- The required condition
#2- What has to be replaced if this condition is getting satisfied
#3- What has to be replaced if the condition in not getting satisfied

In [58]:
age=np.array([-33,-41,54,51,43,56])
age

array([-33, -41,  54,  51,  43,  56])

In [57]:
#Please change all the negative age to 0 and rest to 1

age_new=np.where((age<0),0,1)
age_new

array([0, 0, 1, 1, 1, 1])

In [ ]:
#Please change all those age with negative values to 1 and keep the rest of the value as it is

In [59]:
age_new1=np.where((age<0),1,age)
age_new1

array([ 1,  1, 54, 51, 43, 56])

In [60]:
med_2023['AGE_BUCKET']=np.where(med_2023["Age"]<30,"LESS THAN 30",
                               np.where(med_2023['Age']<=50,"30 to 50",
                                       np.where(med_2023['Age']<=70,"51 to 70","70+")))

In [61]:
med_2023

CUSTOMER_ID    Company        CARD_REG_DATE CARD_ACTIVE  \
0      1000032547      MED +  2006-09-12 00:00:00           Y   
1      1000032548  DR.REDDYS  2006-09-12 00:00:00           Y   
2      1000032549   RELEGARE  2006-09-12 00:00:00           Y   
3      1000032550        GSK  2006-09-12 00:00:00           Y   
4      1000032551        GSK  2006-09-12 00:00:00           Y   
...           ...        ...                  ...         ...   
5107   1000037830   RELEGARE  2008-05-06 00:00:00           Y   
5108   1000037831     APPOLO  2008-05-06 00:00:00           Y   
5109   1000037832        GSK  2008-05-06 00:00:00           Y   
5110   1000037833      MED +  2008-05-06 00:00:00           Y   
5111   1000037834    RANBAXY  2008-05-06 00:00:00           Y   

            FIRST_USE_DTE  firstSTOR TITLE  GENDER  max spent        DOB  ...  \
0     2007-05-12 00:00:00       2587  Mrs.  Female      56.31 1984-09-15  ...   
1     2007-03-12 00:00:00       4341   Ms.  Female     598.95 1974-07-15  ...   
2     2007-02-12 00:00:00       1090  Mrs.  Female       1.56 1959-04-01  ...   
3     2007-03-12 00:00:00       3179   Mr.    Male     115.76 1978-05-16  ...   
4     2007-05-12 00:00:00       3135   Mr.    Male     305.90 1978-12-16  ...   
...                   ...        ...   ...     ...        ...        ...  ...   
5107  2009-05-02 00:00:00       3381   Mr.    Male     198.36 1935-11-23  ...   
5108  2008-10-06 00:00:00       3244  Mrs.  Female      28.09 1956-08-27  ...   
5109  2009-05-04 00:00:00       3381  Mrs.  Female     653.10 1982-05-13  ...   
5110  2009-06-10 00:00:00       3130   Ms.  Female     228.55 1960-01-14  ...   
5111  2009-05-04 00:00:00       3363  Mrs.  Female      26.35 1971-12-22  ...   

     Avgsize spent   CARD_STAT RGSTN_TYPE_IND  NO_OF_TRIPS           TOWN  \
0            17.34  Registered         Online            4        Kyabram   
1            29.32  Registered         Online           17  Hawthorn East   
2             1.56  Registered         Online            1        Revesby   
3            80.49  Registered         Online            2   Willow Grove   
4            24.09  Registered         Online           12      mona vale   
...            ...         ...            ...          ...            ...   
5107         66.12  Registered         Online            3       Kyvalley   
5108         28.09  Registered         Online            1      frankston   
5109         94.77  Registered          Phone            9        KYABRAM   
5110         38.09  Registered         Online            6       Mulgrave   
5111         26.35  Registered     Instore/RF            1        WODONGA   

      EMAIL_IND CONTACT_PREF Average_Qty_PER_ACC  Spent amount    AGE_BUCKET  
0             Y        Email                2.75         69.37  LESS THAN 30  
1             Y        Email                7.29        498.50      30 to 50  
2             Y        Email                2.00          1.56      51 to 70  
3             Y        Email               26.00        160.98      30 to 50  
4             Y        Email                6.33        289.10      30 to 50  
...         ...          ...                 ...           ...           ...  
5107          N          NaN               21.33        198.36           70+  
5108          Y        Email               10.00         28.09      51 to 70  
5109          N          NaN               27.44        852.98      30 to 50  
5110          Y        Email                8.00        228.55      51 to 70  
5111          Y          NaN                7.00         26.35      30 to 50  

[5112 rows x 25 columns]

In [62]:
med_2023['AGE_BUCKET'].value_counts()

30 to 50        2157
51 to 70        1958
70+              520
LESS THAN 30     477
Name: AGE_BUCKET, dtype: int64

In [ ]:
#Premier- 30,70 and gender would be in female or male and spent amount > 400
#Non-premier

In [63]:
med_2023['Cust_seg']=np.where((med_2023['Age'].between(30,70)) & (med_2023["GENDER"].isin(["Female","Male"])) & (med_2023['Spent amount']>=400),"Premier","Non-premier")
med_2023

CUSTOMER_ID    Company        CARD_REG_DATE CARD_ACTIVE  \
0      1000032547      MED +  2006-09-12 00:00:00           Y   
1      1000032548  DR.REDDYS  2006-09-12 00:00:00           Y   
2      1000032549   RELEGARE  2006-09-12 00:00:00           Y   
3      1000032550        GSK  2006-09-12 00:00:00           Y   
4      1000032551        GSK  2006-09-12 00:00:00           Y   
...           ...        ...                  ...         ...   
5107   1000037830   RELEGARE  2008-05-06 00:00:00           Y   
5108   1000037831     APPOLO  2008-05-06 00:00:00           Y   
5109   1000037832        GSK  2008-05-06 00:00:00           Y   
5110   1000037833      MED +  2008-05-06 00:00:00           Y   
5111   1000037834    RANBAXY  2008-05-06 00:00:00           Y   

            FIRST_USE_DTE  firstSTOR TITLE  GENDER  max spent        DOB  ...  \
0     2007-05-12 00:00:00       2587  Mrs.  Female      56.31 1984-09-15  ...   
1     2007-03-12 00:00:00       4341   Ms.  Female     598.95 1974-07-15  ...   
2     2007-02-12 00:00:00       1090  Mrs.  Female       1.56 1959-04-01  ...   
3     2007-03-12 00:00:00       3179   Mr.    Male     115.76 1978-05-16  ...   
4     2007-05-12 00:00:00       3135   Mr.    Male     305.90 1978-12-16  ...   
...                   ...        ...   ...     ...        ...        ...  ...   
5107  2009-05-02 00:00:00       3381   Mr.    Male     198.36 1935-11-23  ...   
5108  2008-10-06 00:00:00       3244  Mrs.  Female      28.09 1956-08-27  ...   
5109  2009-05-04 00:00:00       3381  Mrs.  Female     653.10 1982-05-13  ...   
5110  2009-06-10 00:00:00       3130   Ms.  Female     228.55 1960-01-14  ...   
5111  2009-05-04 00:00:00       3363  Mrs.  Female      26.35 1971-12-22  ...   

       CARD_STAT  RGSTN_TYPE_IND NO_OF_TRIPS           TOWN EMAIL_IND  \
0     Registered          Online           4        Kyabram         Y   
1     Registered          Online          17  Hawthorn East         Y   
2     Registered          Online           1        Revesby         Y   
3     Registered          Online           2   Willow Grove         Y   
4     Registered          Online          12      mona vale         Y   
...          ...             ...         ...            ...       ...   
5107  Registered          Online           3       Kyvalley         N   
5108  Registered          Online           1      frankston         Y   
5109  Registered           Phone           9        KYABRAM         N   
5110  Registered          Online           6       Mulgrave         Y   
5111  Registered      Instore/RF           1        WODONGA         Y   

      CONTACT_PREF Average_Qty_PER_ACC Spent amount    AGE_BUCKET     Cust_seg  
0            Email                2.75        69.37  LESS THAN 30  Non-premier  
1            Email                7.29       498.50      30 to 50      Premier  
2            Email                2.00         1.56      51 to 70  Non-premier  
3            Email               26.00       160.98      30 to 50  Non-premier  
4            Email                6.33       289.10      30 to 50  Non-premier  
...            ...                 ...          ...           ...          ...  
5107           NaN               21.33       198.36           70+  Non-premier  
5108         Email               10.00        28.09      51 to 70  Non-premier  
5109           NaN               27.44       852.98      30 to 50      Premier  
5110         Email                8.00       228.55      51 to 70  Non-premier  
5111           NaN                7.00        26.35      30 to 50  Non-premier  

[5112 rows x 26 columns]

In [64]:
med_2023['Cust_seg'].value_counts()

Non-premier    3962
Premier        1150
Name: Cust_seg, dtype: int64

In [65]:
med_2023['Cust_seg'].value_counts(normalize=True)

Non-premier    0.775039
Premier        0.224961
Name: Cust_seg, dtype: float64