### Numpy Functions

In [1]:
import numpy as np

### Reshape()

In [2]:
a1=np.random.randint(100,150,(4,6))

In [3]:
a1

array([[133, 100, 107, 101, 129, 127],
       [139, 121, 112, 145, 149, 110],
       [106, 103, 139, 100, 133, 111],
       [129, 106, 107, 100, 146, 110]])

In [4]:
a1.shape

(4, 6)

In [5]:
a1.size

24

In [7]:
a2=a1.reshape(2,2,6) 

In [8]:
a2

array([[[133, 100, 107, 101, 129, 127],
        [139, 121, 112, 145, 149, 110]],

       [[106, 103, 139, 100, 133, 111],
        [129, 106, 107, 100, 146, 110]]])

In [9]:
a2.shape

(2, 2, 6)

In [10]:
a2.size

24

In [11]:
a3=a2.reshape(2,12)

In [12]:
a3

array([[133, 100, 107, 101, 129, 127, 139, 121, 112, 145, 149, 110],
       [106, 103, 139, 100, 133, 111, 129, 106, 107, 100, 146, 110]])

In [13]:
a3.shape

(2, 12)

In [14]:
a3.size

24

In [16]:
# a2.reshape(4,8)

### Resize()

In [17]:
a2

array([[[133, 100, 107, 101, 129, 127],
        [139, 121, 112, 145, 149, 110]],

       [[106, 103, 139, 100, 133, 111],
        [129, 106, 107, 100, 146, 110]]])

In [18]:
a2.size

24

In [19]:
a2.resize(12,2)

In [20]:
a2

array([[133, 100],
       [107, 101],
       [129, 127],
       [139, 121],
       [112, 145],
       [149, 110],
       [106, 103],
       [139, 100],
       [133, 111],
       [129, 106],
       [107, 100],
       [146, 110]])

In [21]:
a2.size

24

In [22]:
a2.shape

(12, 2)

In [24]:
# a2.resize(4,8)

In [52]:
a2.resize((4,8),refcheck=False)

In [54]:
a2

array([[171, 192, 153, 186, 103, 157, 117, 191],
       [134, 125, 170, 145, 100, 193, 191, 151],
       [110, 135, 187, 194, 108, 140, 109, 171],
       [  0,   0,   0,   0,   0,   0,   0,   0]])

In [31]:
np.resize(a2,(4,8))

array([[133, 100, 107, 101, 129, 127, 139, 121],
       [112, 145, 149, 110, 106, 103, 139, 100],
       [133, 111, 129, 106, 107, 100, 146, 110],
       [133, 100, 107, 101, 129, 127, 139, 121]])

### Transpose()

In [35]:
a2=np.random.randint(100,200,(4,6))

In [36]:
a2

array([[171, 192, 153, 186, 103, 157],
       [117, 191, 134, 125, 170, 145],
       [100, 193, 191, 151, 110, 135],
       [187, 194, 108, 140, 109, 171]])

In [37]:
a2.transpose()

array([[171, 117, 100, 187],
       [192, 191, 193, 194],
       [153, 134, 191, 108],
       [186, 125, 151, 140],
       [103, 170, 110, 109],
       [157, 145, 135, 171]])

In [38]:
a2.T

array([[171, 117, 100, 187],
       [192, 191, 193, 194],
       [153, 134, 191, 108],
       [186, 125, 151, 140],
       [103, 170, 110, 109],
       [157, 145, 135, 171]])

In [39]:
a2.transpose().shape

(6, 4)

In [40]:
a2.shape

(4, 6)

In [41]:
a3=np.random.randint(100,200,(2,4,6))

In [42]:
a3

array([[[156, 150, 171, 141, 145, 175],
        [170, 137, 192, 120, 145, 119],
        [196, 110, 152, 114, 151, 145],
        [131, 134, 178, 106, 146, 181]],

       [[155, 171, 146, 127, 152, 100],
        [136, 184, 113, 113, 104, 100],
        [108, 190, 157, 150, 105, 171],
        [138, 157, 148, 127, 142, 103]]])

In [44]:
a3.transpose()

array([[[156, 155],
        [170, 136],
        [196, 108],
        [131, 138]],

       [[150, 171],
        [137, 184],
        [110, 190],
        [134, 157]],

       [[171, 146],
        [192, 113],
        [152, 157],
        [178, 148]],

       [[141, 127],
        [120, 113],
        [114, 150],
        [106, 127]],

       [[145, 152],
        [145, 104],
        [151, 105],
        [146, 142]],

       [[175, 100],
        [119, 100],
        [145, 171],
        [181, 103]]])

In [45]:
a3.transpose().shape

(6, 4, 2)

In [46]:
a3.shape

(2, 4, 6)

In [47]:
# (4,2,6)
a3.transpose(1,2,0)

array([[[156, 155],
        [150, 171],
        [171, 146],
        [141, 127],
        [145, 152],
        [175, 100]],

       [[170, 136],
        [137, 184],
        [192, 113],
        [120, 113],
        [145, 104],
        [119, 100]],

       [[196, 108],
        [110, 190],
        [152, 157],
        [114, 150],
        [151, 105],
        [145, 171]],

       [[131, 138],
        [134, 157],
        [178, 148],
        [106, 127],
        [146, 142],
        [181, 103]]])

In [48]:
a3.transpose(1,2,0).shape

(4, 6, 2)

### Swapaxes()

In [55]:
a3

array([[[156, 150, 171, 141, 145, 175],
        [170, 137, 192, 120, 145, 119],
        [196, 110, 152, 114, 151, 145],
        [131, 134, 178, 106, 146, 181]],

       [[155, 171, 146, 127, 152, 100],
        [136, 184, 113, 113, 104, 100],
        [108, 190, 157, 150, 105, 171],
        [138, 157, 148, 127, 142, 103]]])

In [56]:
a3.shape

(2, 4, 6)

In [57]:
a3.swapaxes(1,0)

array([[[156, 150, 171, 141, 145, 175],
        [155, 171, 146, 127, 152, 100]],

       [[170, 137, 192, 120, 145, 119],
        [136, 184, 113, 113, 104, 100]],

       [[196, 110, 152, 114, 151, 145],
        [108, 190, 157, 150, 105, 171]],

       [[131, 134, 178, 106, 146, 181],
        [138, 157, 148, 127, 142, 103]]])

In [58]:
a3.swapaxes(1,0).shape

(4, 2, 6)

### Flatten()

In [59]:
a3

array([[[156, 150, 171, 141, 145, 175],
        [170, 137, 192, 120, 145, 119],
        [196, 110, 152, 114, 151, 145],
        [131, 134, 178, 106, 146, 181]],

       [[155, 171, 146, 127, 152, 100],
        [136, 184, 113, 113, 104, 100],
        [108, 190, 157, 150, 105, 171],
        [138, 157, 148, 127, 142, 103]]])

In [60]:
a3.flatten()

array([156, 150, 171, 141, 145, 175, 170, 137, 192, 120, 145, 119, 196,
       110, 152, 114, 151, 145, 131, 134, 178, 106, 146, 181, 155, 171,
       146, 127, 152, 100, 136, 184, 113, 113, 104, 100, 108, 190, 157,
       150, 105, 171, 138, 157, 148, 127, 142, 103])

In [61]:
a3.flatten(order="F")

array([156, 155, 170, 136, 196, 108, 131, 138, 150, 171, 137, 184, 110,
       190, 134, 157, 171, 146, 192, 113, 152, 157, 178, 148, 141, 127,
       120, 113, 114, 150, 106, 127, 145, 152, 145, 104, 151, 105, 146,
       142, 175, 100, 119, 100, 145, 171, 181, 103])

### Ravel

In [62]:
np.ravel(a3,order="F")

array([156, 155, 170, 136, 196, 108, 131, 138, 150, 171, 137, 184, 110,
       190, 134, 157, 171, 146, 192, 113, 152, 157, 178, 148, 141, 127,
       120, 113, 114, 150, 106, 127, 145, 152, 145, 104, 151, 105, 146,
       142, 175, 100, 119, 100, 145, 171, 181, 103])

### 

### np.nan

In [64]:
a=np.random.randint(10,20,(8,))

In [65]:
a

array([10, 15, 13, 13, 18, 10, 18, 10])

In [66]:
a=np.array([10, 15, 13, 13,"Nan", 18, 10, 18, 10])

In [67]:
a

array(['10', '15', '13', '13', 'Nan', '18', '10', '18', '10'],
      dtype='<U11')

In [71]:
b=np.array([10,20,np.nan,30,40])

In [72]:
b

array([10., 20., nan, 30., 40.])

### np.where

In [77]:
np.where(100>500,100,500)

array(500)

In [79]:
a=100
b=200
c=300

In [81]:
np.where(a>b and a>c, a,  np.where(b>c,b,c))

array(300)

## 

In [73]:
x=np.random.randint(10,30,(5,))

In [74]:
x

array([17, 15, 29, 21, 20])

In [75]:
y=np.random.randint(10,30,(5,))

In [76]:
y

array([26, 28, 12, 17, 10])

In [82]:
np.where(x>y,x,y)

array([26, 28, 29, 21, 20])