### Advantages of NumPy Array over List:
    •	It occupies less memory compare to that of list.
    •	NumPy Array is faster than List.
    •	NumPy array is very flexible compare that of List.

### 	Random.Rand()
    •	np.random.rand()-->Syntax
    •	It accepts the shape as input and generates random values in desired shape.
    •	These values are positive float values.

### 	Random.randn()
    •	np.random.randn()-->Syntax
    •	It accepts the shape as input and generates random values in desired shape.
    •	These values are positive/negative float values.

### 	Random.randint()
    •	np.random.randint(<start>,<end>,(<shape>))-->Syntax
    •	It accepts three parameters,
        o	Start of number range
        o	End of number range
        o	Shape in the form of tuple
    and it generates array in desire shape.

### 	Radndom.choice()
    •	np.random.choice(<Array>,<Shape>,<Pecentage p>)-->Syntax
    •	It accepts three parameters,
        o	Array of numbers
        o	Shape
    o	Percentage
    •	It returns an array with desired number and shape with respective percentage of number presence.

### Indexing & Slicing:

#### Indxing:
    •	If ndim=2
        o	Array[<Row Part(Row Index)>,<Column Part(Column Index)>]
    •	If ndim=3
        o	Array[<3D Block>, <Row Part(Row Index)>,<Column Part(Column Index)>]
#### Slicing:
    •	If ndim=2
        o	Array[<Row Slicing>,<Column Slicing>]
        o	Eg: Array[1:4:1,   3:7:1]
    •	If ndim=3
        o	Array[<3D Slicing><Row Slicing>,<Column Slicing>]
        o	Eg: Array [0:2:1,   1:4:2,    1:5:1]


In [1]:
import numpy as np
import time

### Creating Numpy Array Using Random

In [2]:
r_a1=np.random.rand(3,5)

In [3]:
r_a1

array([[0.49337149, 0.77356783, 0.24256346, 0.66943318, 0.10041317],
       [0.39295492, 0.80205278, 0.05208798, 0.83985308, 0.63858866],
       [0.89493475, 0.93818806, 0.14867319, 0.64359093, 0.70468654]])

In [4]:
r_a2=np.random.rand(2,5,5)

In [5]:
r_a2

array([[[0.34960689, 0.27914967, 0.83090156, 0.98366167, 0.33476602],
        [0.99149846, 0.51859569, 0.1841052 , 0.29266665, 0.52376567],
        [0.34426143, 0.54644358, 0.18106639, 0.1760696 , 0.40153201],
        [0.49765633, 0.50844313, 0.76497999, 0.63095712, 0.25142639],
        [0.67310968, 0.90682734, 0.20956849, 0.75691182, 0.53521893]],

       [[0.3818208 , 0.22978111, 0.01329103, 0.26779268, 0.49413901],
        [0.95331788, 0.82792433, 0.2077286 , 0.50429252, 0.14172937],
        [0.08606038, 0.10835209, 0.71924048, 0.17239638, 0.55624606],
        [0.12864573, 0.56278476, 0.20953084, 0.79324193, 0.31991713],
        [0.05802926, 0.27791894, 0.43456586, 0.48536438, 0.93855346]]])

### Random.Randn 

In [6]:
rn_a=np.random.randn(4,5)

In [7]:
rn_a

array([[ 0.72855738,  0.56126448, -0.52542115,  3.10941266,  2.706746  ],
       [-0.52250932,  1.64262428,  0.7912814 ,  0.60526754,  0.25836255],
       [ 0.2443359 ,  0.15158848,  0.55968839,  0.32091713, -0.27792952],
       [ 0.08423271, -1.95302076, -0.51451486,  1.36303041, -0.29453202]])

In [8]:
rn_a1=np.random.randn(2,4,4)

In [9]:
rn_a1

array([[[-1.32745373, -0.12482   ,  0.8484716 ,  0.39808165],
        [ 0.4462183 ,  0.52173364, -0.13417115, -0.18395839],
        [ 0.43860449, -1.01786853, -2.55706654,  0.73796759],
        [ 1.25720618,  0.47053663, -0.74355393,  1.2722922 ]],

       [[-0.87002728,  2.11811784, -0.8002277 ,  0.43010199],
        [-1.62683276,  0.0766642 ,  1.45261584,  0.47827705],
        [-1.69391449,  0.1496    ,  1.00609153, -0.37126534],
        [-1.21274605,  1.05970539, -0.24979939, -0.92714348]]])

### Random.Randint

In [10]:
i_a1=np.random.randint(5,15,(4,6))

In [11]:
i_a1

array([[13, 13,  7, 12, 12,  8],
       [ 8, 12,  5, 14, 14,  6],
       [ 9, 12,  9, 13, 14,  5],
       [10, 12, 13, 13,  7,  5]])

In [12]:
i_a1.shape

(4, 6)

In [13]:
i_a1.ndim

2

In [14]:
i_a1.size

24

In [15]:
i_a1.dtype

dtype('int32')

In [16]:
i_a2=np.random.randint(5,10,(3,5))

In [17]:
i_a2

array([[5, 5, 9, 9, 6],
       [7, 9, 6, 8, 6],
       [6, 6, 7, 7, 6]])

### Random.Choice

In [18]:
n1=np.arange(5,9)

In [19]:
n1

array([5, 6, 7, 8])

In [20]:
np.random.randint(5,9,(4,6))

array([[7, 6, 8, 5, 7, 7],
       [6, 6, 7, 6, 6, 6],
       [6, 6, 5, 7, 8, 6],
       [7, 8, 5, 5, 6, 7]])

In [21]:
np.random.choice(n1,(3,4),p=[0.1,0.2,0.0,0.7])

array([[8, 8, 5, 6],
       [6, 6, 8, 8],
       [8, 8, 5, 8]])

### Indexing & Slicing

In [22]:
rary1=np.random.randint(2,6,(5,))

In [23]:
rary1

array([4, 2, 5, 3, 4])

In [24]:
rary1[3]

3

In [25]:
ary2=np.random.randint(10,20,(3,5))

In [26]:
ary2

array([[11, 15, 12, 15, 16],
       [13, 11, 11, 19, 16],
       [11, 14, 17, 17, 15]])

In [27]:
ary2[1][4]

16

In [28]:
# ary2[<Rows>,<Column>]
ary2[1,4]

16

In [29]:
ary3=np.random.randint(100,200,(5,9))

In [30]:
ary3

array([[149, 108, 134, 183, 186, 136, 160, 123, 150],
       [142, 124, 159, 135, 157, 156, 141, 128, 128],
       [175, 171, 152, 123, 145, 132, 171, 176, 101],
       [111, 196, 165, 141, 101, 135, 161, 192, 198],
       [160, 142, 122, 113, 176, 121, 184, 184, 112]])

In [31]:
ary3[2,4]

145

### Indexing with Multi Dimension Array

In [32]:
ray3=np.random.randint(100,200,(2,4,6))

In [33]:
ray3

array([[[192, 109, 185, 199, 161, 144],
        [162, 121, 142, 110, 161, 163],
        [140, 191, 104, 186, 195, 134],
        [198, 198, 158, 136, 189, 159]],

       [[150, 159, 168, 107, 195, 157],
        [107, 196, 186, 197, 113, 135],
        [132, 189, 148, 161, 130, 190],
        [176, 132, 177, 117, 103, 118]]])

In [34]:
ray3.ndim

3

In [35]:
ray3.shape

(2, 4, 6)

In [36]:
ray3[1,2,4]

130

In [37]:
ray4=np.random.randint(100,200,(2,3,4,5))

In [38]:
ray4

array([[[[107, 129, 162, 171, 152],
         [104, 187, 112, 184, 122],
         [183, 185, 111, 133, 183],
         [195, 172, 174, 138, 193]],

        [[178, 167, 171, 188, 100],
         [174, 151, 115, 197, 162],
         [106, 122, 108, 175, 132],
         [166, 199, 114, 187, 184]],

        [[119, 124, 155, 139, 146],
         [165, 119, 124, 180, 168],
         [178, 181, 155, 129, 134],
         [145, 145, 126, 132, 141]]],


       [[[140, 133, 128, 156, 133],
         [131, 192, 104, 116, 136],
         [165, 108, 104, 168, 117],
         [102, 135, 162, 115, 173]],

        [[131, 113, 119, 148, 114],
         [147, 122, 146, 113, 122],
         [151, 193, 120, 124, 177],
         [167, 156, 144, 140, 182]],

        [[165, 166, 119, 169, 168],
         [188, 165, 165, 121, 104],
         [184, 164, 122, 120, 168],
         [110, 141, 103, 159, 173]]]])

In [39]:
ray4[0,1,2,2]

108

In [40]:
for i in ray4:
    
    time.sleep(1)
    for j in i:
        print(j)
        time.sleep(1)

[[107 129 162 171 152]
 [104 187 112 184 122]
 [183 185 111 133 183]
 [195 172 174 138 193]]
[[178 167 171 188 100]
 [174 151 115 197 162]
 [106 122 108 175 132]
 [166 199 114 187 184]]
[[119 124 155 139 146]
 [165 119 124 180 168]
 [178 181 155 129 134]
 [145 145 126 132 141]]
[[140 133 128 156 133]
 [131 192 104 116 136]
 [165 108 104 168 117]
 [102 135 162 115 173]]
[[131 113 119 148 114]
 [147 122 146 113 122]
 [151 193 120 124 177]
 [167 156 144 140 182]]
[[165 166 119 169 168]
 [188 165 165 121 104]
 [184 164 122 120 168]
 [110 141 103 159 173]]


### Slicing

In [41]:
r1=np.random.randint(1,10,(8))

In [42]:
r1

array([1, 8, 7, 5, 8, 5, 8, 1])

In [43]:
r1[2:6:1]

array([7, 5, 8, 5])

In [44]:
r1[1:7:1]

array([8, 7, 5, 8, 5, 8])

### 2D Array Slicing

In [45]:
ary3

array([[149, 108, 134, 183, 186, 136, 160, 123, 150],
       [142, 124, 159, 135, 157, 156, 141, 128, 128],
       [175, 171, 152, 123, 145, 132, 171, 176, 101],
       [111, 196, 165, 141, 101, 135, 161, 192, 198],
       [160, 142, 122, 113, 176, 121, 184, 184, 112]])

In [46]:
ary3[1:4:1,   3:7:1]

array([[135, 157, 156, 141],
       [123, 145, 132, 171],
       [141, 101, 135, 161]])

In [47]:
ary3[0:5:1, 1:7:1]

array([[108, 134, 183, 186, 136, 160],
       [124, 159, 135, 157, 156, 141],
       [171, 152, 123, 145, 132, 171],
       [196, 165, 141, 101, 135, 161],
       [142, 122, 113, 176, 121, 184]])

In [48]:
ary3[:]

array([[149, 108, 134, 183, 186, 136, 160, 123, 150],
       [142, 124, 159, 135, 157, 156, 141, 128, 128],
       [175, 171, 152, 123, 145, 132, 171, 176, 101],
       [111, 196, 165, 141, 101, 135, 161, 192, 198],
       [160, 142, 122, 113, 176, 121, 184, 184, 112]])

In [49]:
ary3[: :, 1:7:1]

array([[108, 134, 183, 186, 136, 160],
       [124, 159, 135, 157, 156, 141],
       [171, 152, 123, 145, 132, 171],
       [196, 165, 141, 101, 135, 161],
       [142, 122, 113, 176, 121, 184]])

In [50]:
ary3[1:4:1, 1:8:2]

array([[124, 135, 156, 128],
       [171, 123, 132, 176],
       [196, 141, 135, 192]])

### 3D Array Slicing

In [51]:
ray3

array([[[192, 109, 185, 199, 161, 144],
        [162, 121, 142, 110, 161, 163],
        [140, 191, 104, 186, 195, 134],
        [198, 198, 158, 136, 189, 159]],

       [[150, 159, 168, 107, 195, 157],
        [107, 196, 186, 197, 113, 135],
        [132, 189, 148, 161, 130, 190],
        [176, 132, 177, 117, 103, 118]]])

In [52]:
ray3[0:2:1,1:4:2, 1:5:1]

array([[[121, 142, 110, 161],
        [198, 158, 136, 189]],

       [[196, 186, 197, 113],
        [132, 177, 117, 103]]])

In [53]:
ar=np.random.randint(100,300,(3,5,8))

In [54]:
ar

array([[[255, 123, 291, 128, 135, 207, 192, 228],
        [118, 299, 101, 163, 240, 262, 214, 140],
        [241, 130, 159, 160, 203, 261, 231, 260],
        [221, 288, 131, 136, 169, 147, 119, 211],
        [249, 137, 238, 147, 219, 283, 290, 201]],

       [[237, 148, 148, 257, 210, 197, 220, 228],
        [244, 101, 240, 135, 273, 163, 208, 268],
        [278, 177, 272, 278, 154, 112, 155, 148],
        [235, 190, 292, 112, 263, 185, 229, 166],
        [116, 285, 233, 119, 230, 183, 125, 118]],

       [[285, 124, 154, 129, 248, 151, 274, 273],
        [220, 291, 131, 209, 261, 160, 115, 219],
        [133, 180, 142, 287, 124, 273, 244, 181],
        [244, 251, 259, 283, 207, 288, 140, 159],
        [207, 182, 176, 225, 244, 231, 284, 204]]])

### Advance Indexing

In [55]:
r1

array([1, 8, 7, 5, 8, 5, 8, 1])

In [56]:
#5,8,8,5
r1[[1,3,6,7]]

array([8, 5, 8, 1])

In [57]:
ary3

array([[149, 108, 134, 183, 186, 136, 160, 123, 150],
       [142, 124, 159, 135, 157, 156, 141, 128, 128],
       [175, 171, 152, 123, 145, 132, 171, 176, 101],
       [111, 196, 165, 141, 101, 135, 161, 192, 198],
       [160, 142, 122, 113, 176, 121, 184, 184, 112]])

In [58]:
ary3[[2,1,4,0,3,4,1],  [1,3,4,6,7,8,0]]

array([171, 135, 176, 160, 192, 112, 142])

In [59]:
ar

array([[[255, 123, 291, 128, 135, 207, 192, 228],
        [118, 299, 101, 163, 240, 262, 214, 140],
        [241, 130, 159, 160, 203, 261, 231, 260],
        [221, 288, 131, 136, 169, 147, 119, 211],
        [249, 137, 238, 147, 219, 283, 290, 201]],

       [[237, 148, 148, 257, 210, 197, 220, 228],
        [244, 101, 240, 135, 273, 163, 208, 268],
        [278, 177, 272, 278, 154, 112, 155, 148],
        [235, 190, 292, 112, 263, 185, 229, 166],
        [116, 285, 233, 119, 230, 183, 125, 118]],

       [[285, 124, 154, 129, 248, 151, 274, 273],
        [220, 291, 131, 209, 261, 160, 115, 219],
        [133, 180, 142, 287, 124, 273, 244, 181],
        [244, 251, 259, 283, 207, 288, 140, 159],
        [207, 182, 176, 225, 244, 231, 284, 204]]])

In [60]:
ar[ [0,2,1,1],   [2,0,4,1],         [2,0,6,0]]

array([159, 285, 125, 244])

### Boolean Value

In [61]:
bol1=np.random.randint(50,350,(5,10))

In [62]:
bol1

array([[118, 143, 122,  53, 172, 313,  63, 210, 167, 140],
       [267, 232, 311, 332, 105,  74, 298, 279, 218, 340],
       [325, 120, 319,  99, 171, 234, 243,  63,  59, 209],
       [328, 340, 191,  78, 136,  63, 321,  60, 332, 246],
       [249, 290, 148, 172, 248, 134, 138, 144, 281, 158]])

In [63]:
bol1<100

array([[False, False, False,  True, False, False,  True, False, False,
        False],
       [False, False, False, False, False,  True, False, False, False,
        False],
       [False, False, False,  True, False, False, False,  True,  True,
        False],
       [False, False, False,  True, False,  True, False,  True, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False]])

In [64]:
bol1[bol1<100]

array([53, 63, 74, 99, 63, 59, 78, 63, 60])

In [65]:
bol1>200

array([[False, False, False, False, False,  True, False,  True, False,
        False],
       [ True,  True,  True,  True, False, False,  True,  True,  True,
         True],
       [ True, False,  True, False, False,  True,  True, False, False,
         True],
       [ True,  True, False, False, False, False,  True, False,  True,
         True],
       [ True,  True, False, False,  True, False, False, False,  True,
        False]])

In [66]:
bol1[bol1>200]

array([313, 210, 267, 232, 311, 332, 298, 279, 218, 340, 325, 319, 234,
       243, 209, 328, 340, 321, 332, 246, 249, 290, 248, 281])

In [67]:
(bol1>100) & (bol1<200)

array([[ True,  True,  True, False,  True, False, False, False,  True,
         True],
       [False, False, False, False,  True, False, False, False, False,
        False],
       [False,  True, False, False,  True, False, False, False, False,
        False],
       [False, False,  True, False,  True, False, False, False, False,
        False],
       [False, False,  True,  True, False,  True,  True,  True, False,
         True]])

In [68]:
bol1[(bol1>100) & (bol1<200)]

array([118, 143, 122, 172, 167, 140, 105, 120, 171, 191, 136, 148, 172,
       134, 138, 144, 158])

In [69]:
(bol1<100) | (bol1>200)

array([[False, False, False,  True, False,  True,  True,  True, False,
        False],
       [ True,  True,  True,  True, False,  True,  True,  True,  True,
         True],
       [ True, False,  True,  True, False,  True,  True,  True,  True,
         True],
       [ True,  True, False,  True, False,  True,  True,  True,  True,
         True],
       [ True,  True, False, False,  True, False, False, False,  True,
        False]])

In [70]:
bol1[(bol1<100) | (bol1>200)]

array([ 53, 313,  63, 210, 267, 232, 311, 332,  74, 298, 279, 218, 340,
       325, 319,  99, 234, 243,  63,  59, 209, 328, 340,  78,  63, 321,
        60, 332, 246, 249, 290, 248, 281])

### Numpy occupy less memory

In [71]:
r1

array([1, 8, 7, 5, 8, 5, 8, 1])

In [72]:
len(r1)

8

In [73]:
r1.size

8

In [74]:
r1.itemsize

4

In [75]:
r1.dtype

dtype('int32')

In [76]:
r1.itemsize*r1.size

32

In [77]:
list=[8, 5, 1, 8, 6, 9, 8, 5]

In [78]:
type(list)

list

In [79]:
import sys

In [80]:
sys.getsizeof(8)

28

In [81]:
sys.getsizeof(1)

28

In [82]:
len(list)

8

In [83]:
len(list)*sys.getsizeof(8)

224

### Speed Check of Numpy over list

In [84]:
n=10000

In [87]:
a3=np.arange(n)
a4=np.arange(n)

In [88]:
a3

array([   0,    1,    2, ..., 9997, 9998, 9999])

In [89]:
a4

array([   0,    1,    2, ..., 9997, 9998, 9999])

In [98]:
st=time.time()
t=a3+a4
et=time.time()
print((et-st)*1000)

0.0
