In [1]:
import numpy as np

### Np.Round

In [8]:
a1=np.random.randint(10,20,(5))

In [9]:
a1

array([17, 11, 14, 17, 13])

In [10]:
a1.mean()

14.4

In [11]:
num=43.36578

In [12]:
np.round(num,2)

43.37

In [13]:
np.round(num,1)

43.4

### Np.Insert

In [14]:
a1

array([17, 11, 14, 17, 13])

In [15]:
np.insert(a1,2,23,axis=None)

array([17, 11, 23, 14, 17, 13])

In [16]:
# Insert Multiple Value at Single Index
np.insert(a1,2,[55,66],axis=None)

array([17, 11, 55, 66, 14, 17, 13])

In [17]:
# Single Value in Multiple Index
np.insert(a1,[2,4],59,axis=None)

array([17, 11, 59, 14, 17, 59, 13])

In [18]:
# Insert Multiple Value in Multiple Index
np.insert(a1,[1,3],[100,200],axis=None)

array([ 17, 100,  11,  14, 200,  17,  13])

### 2D Array Insertion

In [20]:
a2=np.random.randint(100,200,(4,6))

In [21]:
a2

array([[185, 171, 152, 128, 127, 162],
       [170, 114, 139, 178, 189, 168],
       [197, 174, 111, 168, 129, 122],
       [165, 163, 198, 112, 170, 197]])

In [22]:
np.insert(a2,2,[22,22,22,22,22,22])

array([185, 171,  22,  22,  22,  22,  22,  22, 152, 128, 127, 162, 170,
       114, 139, 178, 189, 168, 197, 174, 111, 168, 129, 122, 165, 163,
       198, 112, 170, 197])

In [23]:
np.insert(a2,2,[22,22,22,22,22,22],axis=0)

array([[185, 171, 152, 128, 127, 162],
       [170, 114, 139, 178, 189, 168],
       [ 22,  22,  22,  22,  22,  22],
       [197, 174, 111, 168, 129, 122],
       [165, 163, 198, 112, 170, 197]])

In [27]:
np.insert(a2,3,[100,100,100,100],axis=1)

array([[185, 171, 152, 100, 128, 127, 162],
       [170, 114, 139, 100, 178, 189, 168],
       [197, 174, 111, 100, 168, 129, 122],
       [165, 163, 198, 100, 112, 170, 197]])

In [35]:
np.insert(a2,4,[100,100,100,100],axis=1)

array([[185, 171, 152, 128, 100, 127, 162],
       [170, 114, 139, 178, 100, 189, 168],
       [197, 174, 111, 168, 100, 129, 122],
       [165, 163, 198, 112, 100, 170, 197]])

In [36]:
np.insert(a2,3,55,axis=1)

array([[185, 171, 152,  55, 128, 127, 162],
       [170, 114, 139,  55, 178, 189, 168],
       [197, 174, 111,  55, 168, 129, 122],
       [165, 163, 198,  55, 112, 170, 197]])

In [37]:
np.insert(a2,2,55,axis=0)

array([[185, 171, 152, 128, 127, 162],
       [170, 114, 139, 178, 189, 168],
       [ 55,  55,  55,  55,  55,  55],
       [197, 174, 111, 168, 129, 122],
       [165, 163, 198, 112, 170, 197]])

### Np.Append

In [38]:
a1

array([17, 11, 14, 17, 13])

In [39]:
np.append(a1,1000,axis=None)

array([  17,   11,   14,   17,   13, 1000])

In [40]:
a2

array([[185, 171, 152, 128, 127, 162],
       [170, 114, 139, 178, 189, 168],
       [197, 174, 111, 168, 129, 122],
       [165, 163, 198, 112, 170, 197]])

In [42]:
np.append(a2,[[5,3,7,8,6,9]],axis=0)

array([[185, 171, 152, 128, 127, 162],
       [170, 114, 139, 178, 189, 168],
       [197, 174, 111, 168, 129, 122],
       [165, 163, 198, 112, 170, 197],
       [  5,   3,   7,   8,   6,   9]])

In [45]:
np.append(a2,[[5],[3],[7],[8]],axis=1)

array([[185, 171, 152, 128, 127, 162,   5],
       [170, 114, 139, 178, 189, 168,   3],
       [197, 174, 111, 168, 129, 122,   7],
       [165, 163, 198, 112, 170, 197,   8]])

### Np.Delete

In [46]:
a3=np.random.randint(10,20,(10,))

In [47]:
a3

array([11, 16, 13, 19, 14, 16, 14, 18, 16, 10])

In [49]:
np.delete(a3,3,axis=None)

array([11, 16, 13, 14, 16, 14, 18, 16, 10])

In [50]:
a2

array([[185, 171, 152, 128, 127, 162],
       [170, 114, 139, 178, 189, 168],
       [197, 174, 111, 168, 129, 122],
       [165, 163, 198, 112, 170, 197]])

In [52]:
a22=np.insert(a2,2,999,axis=0)

In [53]:
a22

array([[185, 171, 152, 128, 127, 162],
       [170, 114, 139, 178, 189, 168],
       [999, 999, 999, 999, 999, 999],
       [197, 174, 111, 168, 129, 122],
       [165, 163, 198, 112, 170, 197]])

In [54]:
np.delete(a22,2,axis=0)

array([[185, 171, 152, 128, 127, 162],
       [170, 114, 139, 178, 189, 168],
       [197, 174, 111, 168, 129, 122],
       [165, 163, 198, 112, 170, 197]])

In [55]:
np.delete(a22,3,axis=1)

array([[185, 171, 152, 127, 162],
       [170, 114, 139, 189, 168],
       [999, 999, 999, 999, 999],
       [197, 174, 111, 129, 122],
       [165, 163, 198, 170, 197]])

### Np.Concatenate

In [56]:
a1

array([17, 11, 14, 17, 13])

In [57]:
a3

array([11, 16, 13, 19, 14, 16, 14, 18, 16, 10])

In [ ]:
# np.concatenate(a1,a3)

In [58]:
a2

array([[185, 171, 152, 128, 127, 162],
       [170, 114, 139, 178, 189, 168],
       [197, 174, 111, 168, 129, 122],
       [165, 163, 198, 112, 170, 197]])

In [59]:
a4=np.random.randint(10,20,(4,5))

In [60]:
a4

array([[13, 12, 12, 18, 16],
       [16, 15, 15, 11, 11],
       [14, 15, 15, 17, 11],
       [18, 18, 18, 13, 13]])

In [ ]:
# np.concatenate(a2,a4) By default axis=0

In [ ]:
# np.concatenate(a2,a4,axis=0)

In [61]:
np.concatenate((a2,a4),axis=1)

array([[185, 171, 152, 128, 127, 162,  13,  12,  12,  18,  16],
       [170, 114, 139, 178, 189, 168,  16,  15,  15,  11,  11],
       [197, 174, 111, 168, 129, 122,  14,  15,  15,  17,  11],
       [165, 163, 198, 112, 170, 197,  18,  18,  18,  13,  13]])

### 

In [62]:
a5=np.random.randint(10,20,(5,3))

In [63]:
a5

array([[10, 12, 19],
       [11, 16, 18],
       [18, 15, 16],
       [11, 16, 11],
       [14, 14, 10]])

In [64]:
a6=np.random.randint(10,20,(4,3))

In [65]:
a6

array([[19, 11, 11],
       [17, 14, 19],
       [16, 13, 18],
       [18, 16, 10]])

In [68]:
# np.concatenate((a5,a6),axis=1)

In [67]:
np.concatenate((a5,a6),axis=0)

array([[10, 12, 19],
       [11, 16, 18],
       [18, 15, 16],
       [11, 16, 11],
       [14, 14, 10],
       [19, 11, 11],
       [17, 14, 19],
       [16, 13, 18],
       [18, 16, 10]])

In [69]:
n1=np.random.randint(10,20,(5,6))

In [70]:
n2=np.random.randint(20,40,(6,6))

In [71]:
n3=np.random.randint(40,60,(5,6))

In [72]:
n1

array([[18, 13, 16, 18, 10, 18],
       [16, 12, 17, 13, 17, 14],
       [11, 11, 10, 12, 19, 16],
       [18, 16, 15, 18, 18, 16],
       [15, 10, 17, 14, 16, 12]])

In [73]:
n2

array([[23, 37, 25, 21, 25, 37],
       [29, 29, 23, 32, 24, 38],
       [24, 39, 38, 23, 23, 32],
       [31, 37, 20, 37, 36, 31],
       [28, 22, 37, 36, 31, 38],
       [36, 21, 21, 25, 33, 20]])

In [74]:
n3

array([[46, 55, 47, 50, 57, 58],
       [54, 59, 57, 47, 55, 42],
       [51, 45, 48, 56, 49, 52],
       [50, 43, 55, 56, 41, 58],
       [45, 42, 50, 40, 41, 50]])

In [75]:
n1.shape

(5, 6)

In [76]:
n2.shape

(6, 6)

In [77]:
n3.shape

(5, 6)

In [78]:
np.concatenate((n1,n2),axis=0)

array([[18, 13, 16, 18, 10, 18],
       [16, 12, 17, 13, 17, 14],
       [11, 11, 10, 12, 19, 16],
       [18, 16, 15, 18, 18, 16],
       [15, 10, 17, 14, 16, 12],
       [23, 37, 25, 21, 25, 37],
       [29, 29, 23, 32, 24, 38],
       [24, 39, 38, 23, 23, 32],
       [31, 37, 20, 37, 36, 31],
       [28, 22, 37, 36, 31, 38],
       [36, 21, 21, 25, 33, 20]])

In [80]:
# np.concatenate((n1,n2),axis=1)

## 

In [ ]:
# np.hstack((n1,n2))   # Axis=1

In [81]:
np.vstack((n1,n2)) # Axis=0

array([[18, 13, 16, 18, 10, 18],
       [16, 12, 17, 13, 17, 14],
       [11, 11, 10, 12, 19, 16],
       [18, 16, 15, 18, 18, 16],
       [15, 10, 17, 14, 16, 12],
       [23, 37, 25, 21, 25, 37],
       [29, 29, 23, 32, 24, 38],
       [24, 39, 38, 23, 23, 32],
       [31, 37, 20, 37, 36, 31],
       [28, 22, 37, 36, 31, 38],
       [36, 21, 21, 25, 33, 20]])

In [83]:
np.concatenate((n1,n3),axis=1)

array([[18, 13, 16, 18, 10, 18, 46, 55, 47, 50, 57, 58],
       [16, 12, 17, 13, 17, 14, 54, 59, 57, 47, 55, 42],
       [11, 11, 10, 12, 19, 16, 51, 45, 48, 56, 49, 52],
       [18, 16, 15, 18, 18, 16, 50, 43, 55, 56, 41, 58],
       [15, 10, 17, 14, 16, 12, 45, 42, 50, 40, 41, 50]])

In [93]:
n11=np.hstack((n1,n3))

In [94]:
n11

array([[18, 13, 16, 18, 10, 18, 46, 55, 47, 50, 57, 58],
       [16, 12, 17, 13, 17, 14, 54, 59, 57, 47, 55, 42],
       [11, 11, 10, 12, 19, 16, 51, 45, 48, 56, 49, 52],
       [18, 16, 15, 18, 18, 16, 50, 43, 55, 56, 41, 58],
       [15, 10, 17, 14, 16, 12, 45, 42, 50, 40, 41, 50]])

### Np.Split

In [86]:
a3

array([17, 11, 14, 17, 13])

In [88]:
a3.size

10

In [89]:
np.split(a3,2)

[array([11, 16, 13, 19, 14]), array([16, 14, 18, 16, 10])]

In [91]:
# np.split(a3,3)

In [92]:
np.split(a3,5)

[array([11, 16]),
 array([13, 19]),
 array([14, 16]),
 array([14, 18]),
 array([16, 10])]

In [95]:
n11

array([[18, 13, 16, 18, 10, 18, 46, 55, 47, 50, 57, 58],
       [16, 12, 17, 13, 17, 14, 54, 59, 57, 47, 55, 42],
       [11, 11, 10, 12, 19, 16, 51, 45, 48, 56, 49, 52],
       [18, 16, 15, 18, 18, 16, 50, 43, 55, 56, 41, 58],
       [15, 10, 17, 14, 16, 12, 45, 42, 50, 40, 41, 50]])

In [96]:
np.split(n11,5)

[array([[18, 13, 16, 18, 10, 18, 46, 55, 47, 50, 57, 58]]),
 array([[16, 12, 17, 13, 17, 14, 54, 59, 57, 47, 55, 42]]),
 array([[11, 11, 10, 12, 19, 16, 51, 45, 48, 56, 49, 52]]),
 array([[18, 16, 15, 18, 18, 16, 50, 43, 55, 56, 41, 58]]),
 array([[15, 10, 17, 14, 16, 12, 45, 42, 50, 40, 41, 50]])]

In [99]:
# np.split(n11,3)

In [100]:
np.split(n11,12,axis=1)

[array([[18],
        [16],
        [11],
        [18],
        [15]]),
 array([[13],
        [12],
        [11],
        [16],
        [10]]),
 array([[16],
        [17],
        [10],
        [15],
        [17]]),
 array([[18],
        [13],
        [12],
        [18],
        [14]]),
 array([[10],
        [17],
        [19],
        [18],
        [16]]),
 array([[18],
        [14],
        [16],
        [16],
        [12]]),
 array([[46],
        [54],
        [51],
        [50],
        [45]]),
 array([[55],
        [59],
        [45],
        [43],
        [42]]),
 array([[47],
        [57],
        [48],
        [55],
        [50]]),
 array([[50],
        [47],
        [56],
        [56],
        [40]]),
 array([[57],
        [55],
        [49],
        [41],
        [41]]),
 array([[58],
        [42],
        [52],
        [58],
        [50]])]

In [101]:
np.split(n11,6,axis=1)

[array([[18, 13],
        [16, 12],
        [11, 11],
        [18, 16],
        [15, 10]]),
 array([[16, 18],
        [17, 13],
        [10, 12],
        [15, 18],
        [17, 14]]),
 array([[10, 18],
        [17, 14],
        [19, 16],
        [18, 16],
        [16, 12]]),
 array([[46, 55],
        [54, 59],
        [51, 45],
        [50, 43],
        [45, 42]]),
 array([[47, 50],
        [57, 47],
        [48, 56],
        [55, 56],
        [50, 40]]),
 array([[57, 58],
        [55, 42],
        [49, 52],
        [41, 58],
        [41, 50]])]

In [102]:
np.split(n11,4,axis=1)

[array([[18, 13, 16],
        [16, 12, 17],
        [11, 11, 10],
        [18, 16, 15],
        [15, 10, 17]]),
 array([[18, 10, 18],
        [13, 17, 14],
        [12, 19, 16],
        [18, 18, 16],
        [14, 16, 12]]),
 array([[46, 55, 47],
        [54, 59, 57],
        [51, 45, 48],
        [50, 43, 55],
        [45, 42, 50]]),
 array([[50, 57, 58],
        [47, 55, 42],
        [56, 49, 52],
        [56, 41, 58],
        [40, 41, 50]])]

In [103]:
np.split(n11,2,axis=1)

[array([[18, 13, 16, 18, 10, 18],
        [16, 12, 17, 13, 17, 14],
        [11, 11, 10, 12, 19, 16],
        [18, 16, 15, 18, 18, 16],
        [15, 10, 17, 14, 16, 12]]),
 array([[46, 55, 47, 50, 57, 58],
        [54, 59, 57, 47, 55, 42],
        [51, 45, 48, 56, 49, 52],
        [50, 43, 55, 56, 41, 58],
        [45, 42, 50, 40, 41, 50]])]

In [106]:
np.vsplit(n11,5) # Split with axis=0

[array([[18, 13, 16, 18, 10, 18, 46, 55, 47, 50, 57, 58]]),
 array([[16, 12, 17, 13, 17, 14, 54, 59, 57, 47, 55, 42]]),
 array([[11, 11, 10, 12, 19, 16, 51, 45, 48, 56, 49, 52]]),
 array([[18, 16, 15, 18, 18, 16, 50, 43, 55, 56, 41, 58]]),
 array([[15, 10, 17, 14, 16, 12, 45, 42, 50, 40, 41, 50]])]

In [107]:
np.hsplit(n11,2) # Split with axis=1

[array([[18, 13, 16, 18, 10, 18],
        [16, 12, 17, 13, 17, 14],
        [11, 11, 10, 12, 19, 16],
        [18, 16, 15, 18, 18, 16],
        [15, 10, 17, 14, 16, 12]]),
 array([[46, 55, 47, 50, 57, 58],
        [54, 59, 57, 47, 55, 42],
        [51, 45, 48, 56, 49, 52],
        [50, 43, 55, 56, 41, 58],
        [45, 42, 50, 40, 41, 50]])]

# ***

In [108]:
a3

array([11, 16, 13, 19, 14, 16, 14, 18, 16, 10])

In [109]:
a3.reshape(2,5)

array([[11, 16, 13, 19, 14],
       [16, 14, 18, 16, 10]])

In [122]:
w=a3.reshape(1,-1)

In [123]:
w

array([[11, 16, 13, 19, 14, 16, 14, 18, 16, 10]])

In [124]:
a3.shape

(10,)

In [125]:
w.shape

(1, 10)

In [127]:
w1=a3.reshape(-1,1)

In [128]:
w1

array([[11],
       [16],
       [13],
       [19],
       [14],
       [16],
       [14],
       [18],
       [16],
       [10]])

In [129]:
w1.shape

(10, 1)

In [130]:
w1.ndim

2

In [131]:
w.ndim

2

In [132]:
a3.ndim

1

### Mean, Max,Min, Std, Unique

In [133]:
a1

array([17, 11, 14, 17, 13])

In [134]:
a1.max()

17

In [135]:
a1.min()

11

In [136]:
a1.mean()

14.4

In [138]:
np.unique(a1)

array([11, 13, 14, 17])

In [140]:
np.unique(a1,return_counts=True)

(array([11, 13, 14, 17]), array([1, 1, 1, 2], dtype=int64))

In [141]:
a1.std()

2.33238075793812

### Expand Dimension

In [142]:
a1

array([17, 11, 14, 17, 13])

In [144]:
aw=np.expand_dims(a1,axis=0)

In [145]:
aw

array([[17, 11, 14, 17, 13]])

In [149]:
aw.shape

(1, 5)

In [147]:
aw1=np.expand_dims(a1,axis=1)

In [148]:
aw1

array([[17],
       [11],
       [14],
       [17],
       [13]])

In [150]:
aw1.shape

(5, 1)

### Squeeze

In [151]:
np.squeeze(aw)

array([17, 11, 14, 17, 13])

In [152]:
np.squeeze(aw).shape

(5,)

# 

In [153]:
q=np.array([3,4,5,0,6,7,8,0,9])

In [154]:
q

array([3, 4, 5, 0, 6, 7, 8, 0, 9])

In [155]:
np.count_nonzero(q)

7

In [156]:
np.argwhere(q)

array([[0],
       [1],
       [2],
       [4],
       [5],
       [6],
       [8]], dtype=int64)

In [157]:
np.argmax(q)

8

In [158]:
a2

array([[185, 171, 152, 128, 127, 162],
       [170, 114, 139, 178, 189, 168],
       [197, 174, 111, 168, 129, 122],
       [165, 163, 198, 112, 170, 197]])

In [159]:
np.argmax(a2)

20

In [160]:
np.argmin(q)

3

In [161]:
np.flip(a2)

array([[197, 170, 112, 198, 163, 165],
       [122, 129, 168, 111, 174, 197],
       [168, 189, 178, 139, 114, 170],
       [162, 127, 128, 152, 171, 185]])

In [162]:
np.flip(a2,axis=0)

array([[165, 163, 198, 112, 170, 197],
       [197, 174, 111, 168, 129, 122],
       [170, 114, 139, 178, 189, 168],
       [185, 171, 152, 128, 127, 162]])

In [163]:
np.flip(a2,axis=1)

array([[162, 127, 128, 152, 171, 185],
       [168, 189, 178, 139, 114, 170],
       [122, 129, 168, 111, 174, 197],
       [197, 170, 112, 198, 163, 165]])

In [164]:
np.fliplr(a2) # Axis=1

array([[162, 127, 128, 152, 171, 185],
       [168, 189, 178, 139, 114, 170],
       [122, 129, 168, 111, 174, 197],
       [197, 170, 112, 198, 163, 165]])

In [165]:
np.flipud(a2) # Axis=0

array([[165, 163, 198, 112, 170, 197],
       [197, 174, 111, 168, 129, 122],
       [170, 114, 139, 178, 189, 168],
       [185, 171, 152, 128, 127, 162]])

## 

In [166]:
a2

array([[185, 171, 152, 128, 127, 162],
       [170, 114, 139, 178, 189, 168],
       [197, 174, 111, 168, 129, 122],
       [165, 163, 198, 112, 170, 197]])

In [167]:
np.savetxt("a2.txt",a2)

In [168]:
np.loadtxt("a2.txt")

array([[185., 171., 152., 128., 127., 162.],
       [170., 114., 139., 178., 189., 168.],
       [197., 174., 111., 168., 129., 122.],
       [165., 163., 198., 112., 170., 197.]])

In [169]:
np.repeat(9,5)

array([9, 9, 9, 9, 9])

In [170]:
np.repeat([9,2],5)

array([9, 9, 9, 9, 9, 2, 2, 2, 2, 2])

In [172]:
a33=np.array([17, 11, 14, 17, 13])

In [173]:
a33

array([17, 11, 14, 17, 13])

In [175]:
a44=np.array([17, 10, 13, 17, 12])

In [176]:
a44

array([17, 10, 13, 17, 12])

In [177]:
np.equal(a44,a33)

array([ True, False, False,  True, False])