### Operations

In [98]:
import numpy as np

In [3]:
a1=np.random.randint(10,20,(5,))

In [4]:
b1=np.random.randint(1,10,(5,))

In [5]:
a1

array([11, 11, 17, 10, 12])

In [6]:
b1

array([1, 7, 9, 8, 6])

In [7]:
a1+b1

array([12, 18, 26, 18, 18])

In [8]:
x1=np.random.randint(10,20,(8,))

In [10]:
x1

array([12, 14, 13, 13, 12, 17, 16, 10])

In [11]:
a1+8

array([19, 19, 25, 18, 20])

In [12]:
np.add(a1,b1)

array([12, 18, 26, 18, 18])

In [13]:
a1-b1

array([10,  4,  8,  2,  6])

In [14]:
np.subtract(a1,b1)

array([10,  4,  8,  2,  6])

In [15]:
a1*b1

array([ 11,  77, 153,  80,  72])

In [16]:
np.multiply(a1,b1)

array([ 11,  77, 153,  80,  72])

In [17]:
a1/b1

array([11.        ,  1.57142857,  1.88888889,  1.25      ,  2.        ])

In [18]:
np.divide(a1,b1)

array([11.        ,  1.57142857,  1.88888889,  1.25      ,  2.        ])

### 2D Array

In [20]:
a2=np.random.randint(3,6,(2,2))

In [21]:
b2=np.random.randint(6,11,(2,2))

In [22]:
a2

array([[5, 5],
       [3, 5]])

In [23]:
b2

array([[ 6,  9],
       [10, 10]])

In [25]:
a2+b2

array([[11, 14],
       [13, 15]])

In [26]:
a2*b2

array([[30, 45],
       [30, 50]])

In [27]:
a2-b2

array([[-1, -4],
       [-7, -5]])

### 2D with Different Shape

In [28]:
x2=np.random.randint(1,10,(3,3))

In [29]:
x2

array([[2, 6, 8],
       [8, 7, 6],
       [2, 7, 6]])

In [31]:
# a2+x2

### Shape--> Same
### Dimension--> Same

In [32]:
a1

array([11, 11, 17, 10, 12])

In [34]:
a1.shape

(5,)

In [35]:
a1.ndim

1

In [36]:
b1.ndim

1

In [37]:
b1.shape

(5,)

In [38]:
a1+b1

array([12, 18, 26, 18, 18])

In [39]:
a1-b1

array([10,  4,  8,  2,  6])

In [40]:
a1*b1

array([ 11,  77, 153,  80,  72])

In [41]:
a1/b1

array([11.        ,  1.57142857,  1.88888889,  1.25      ,  2.        ])

### 

In [42]:
a2

array([[5, 5],
       [3, 5]])

In [43]:
b2

array([[ 6,  9],
       [10, 10]])

In [44]:
a2.shape

(2, 2)

In [45]:
b2.shape

(2, 2)

In [46]:
a2.ndim

2

In [47]:
b2.ndim

2

In [48]:
a2+b2

array([[11, 14],
       [13, 15]])

In [49]:
a2-b2

array([[-1, -4],
       [-7, -5]])

In [50]:
a2*b2

array([[30, 45],
       [30, 50]])

In [51]:
a2/b2

array([[0.83333333, 0.55555556],
       [0.3       , 0.5       ]])

In [52]:
a2.dot(b2)

array([[80, 95],
       [68, 77]])

In [53]:
a3=np.random.randint(1,20,(3,3))

In [54]:
b3=np.random.randint(1,20,(3,3))

In [57]:
print(a3)
print("Shape: ",a3.shape)
print("Dimension: ",a3.ndim)

[[ 7  9  3]
 [13 19 15]
 [19  7 19]]
Shape:  (3, 3)
Dimension:  2


In [58]:
print(b3)
print("Shape: ",b3.shape)
print("Dimension: ",b3.ndim)

[[ 4 12 13]
 [17 19  2]
 [13 10 10]]
Shape:  (3, 3)
Dimension:  2


In [59]:
a3+b3

array([[11, 21, 16],
       [30, 38, 17],
       [32, 17, 29]])

In [60]:
a3-b3

array([[  3,  -3, -10],
       [ -4,   0,  13],
       [  6,  -3,   9]])

In [61]:
a3*b3

array([[ 28, 108,  39],
       [221, 361,  30],
       [247,  70, 190]])

In [62]:
a3/b3

array([[1.75      , 0.75      , 0.23076923],
       [0.76470588, 1.        , 7.5       ],
       [1.46153846, 0.7       , 1.9       ]])

### Dimension--> Same
### Shape--> Different

In [63]:
x1

array([12, 14, 13, 13, 12, 17, 16, 10])

In [64]:
a1

array([11, 11, 17, 10, 12])

In [66]:
# a1+x1

In [67]:
a1+8

array([19, 19, 25, 18, 20])

In [68]:
a2

array([[5, 5],
       [3, 5]])

In [69]:
x2

array([[2, 6, 8],
       [8, 7, 6],
       [2, 7, 6]])

In [71]:
# a2+x2

In [72]:
y2=np.random.randint(10,20,(3,1))


In [73]:
y2

array([[18],
       [10],
       [15]])

In [74]:
y2.shape

(3, 1)

In [75]:
y2.ndim

2

In [76]:
x2+y2

array([[20, 24, 26],
       [18, 17, 16],
       [17, 22, 21]])

In [77]:
# a2+y2

In [81]:
x3=np.random.randint(1,100,(1,2))

In [80]:
x3

array([[12,  2]])

In [82]:
x3.shape

(1, 2)

In [83]:
x3.ndim

2

In [84]:
a2+x3

array([[ 9, 32],
       [ 7, 32]])

### Shape--> Different
### Dimension--> Different

In [86]:
a3.ndim

2

In [89]:
a1.ndim

1

In [90]:
a1.shape

(5,)

In [91]:
a3.shape

(3, 3)

In [93]:
# a3+a1

In [94]:
np1=np.random.randint(100,200,(3,2,5))

In [100]:
np3=np.random.randint(100,200,(5,))

In [102]:
np1+np3

array([[[297, 309, 246, 280, 209],
        [310, 227, 309, 312, 237]],

       [[243, 231, 236, 260, 266],
        [282, 288, 290, 258, 202]],

       [[327, 320, 248, 285, 273],
        [313, 271, 231, 242, 292]]])