In [1]:
import numpy as np

## Numpy Useful Functions

### np.sort 
     Return a sorted copy of an array

In [39]:
a=np.random.randint(1,100,15)
b=np.random.randint(1,100,(6,4))

In [40]:
a

array([21, 26, 43, 76, 11, 58, 91,  9, 14, 96, 40, 83, 99, 76, 58])

In [4]:
b

array([[ 9, 28, 64, 40],
       [53, 83, 97, 47],
       [ 9, 10, 44, 62],
       [47, 66, 20, 63],
       [60, 17, 42, 87],
       [88, 34, 97, 62]])

In [5]:
np.sort(a) # (Ascending to Descending)

array([ 9, 21, 31, 33, 47, 49, 57, 73, 74, 75, 77, 89, 90, 92, 96])

In [6]:
np.sort(b) # Row wise Sorting (Ascending to Descending)

array([[ 9, 28, 40, 64],
       [47, 53, 83, 97],
       [ 9, 10, 44, 62],
       [20, 47, 63, 66],
       [17, 42, 60, 87],
       [34, 62, 88, 97]])

In [7]:
np.sort(b,axis=0) # Column wise Sorting (Ascending to Descending)

array([[ 9, 10, 20, 40],
       [ 9, 17, 42, 47],
       [47, 28, 44, 62],
       [53, 34, 64, 62],
       [60, 66, 97, 63],
       [88, 83, 97, 87]])

In [8]:
np.sort(a)[::-1]  # Descending to Ascending

array([96, 92, 90, 89, 77, 75, 74, 73, 57, 49, 47, 33, 31, 21,  9])

### np.append
     The numpy.append() appends values along the mentioned axis at the end of the array

In [41]:
a

array([21, 26, 43, 76, 11, 58, 91,  9, 14, 96, 40, 83, 99, 76, 58])

In [10]:
np.append(a,200)

array([ 90,  89,  33,   9,  96,  77,  21,  75,  47,  31,  49,  92,  73,
        57,  74, 200])

In [11]:
np.append(a,[2,4,5])

array([90, 89, 33,  9, 96, 77, 21, 75, 47, 31, 49, 92, 73, 57, 74,  2,  4,
        5])

In [12]:
b

array([[ 9, 28, 64, 40],
       [53, 83, 97, 47],
       [ 9, 10, 44, 62],
       [47, 66, 20, 63],
       [60, 17, 42, 87],
       [88, 34, 97, 62]])

In [13]:
np.append(b,1) # First it convert it to 1D array then append the value in the last.

array([ 9, 28, 64, 40, 53, 83, 97, 47,  9, 10, 44, 62, 47, 66, 20, 63, 60,
       17, 42, 87, 88, 34, 97, 62,  1])

In [14]:
np.append(b,np.ones((b.shape[0],1)),axis=1) # Column wise Append

array([[ 9., 28., 64., 40.,  1.],
       [53., 83., 97., 47.,  1.],
       [ 9., 10., 44., 62.,  1.],
       [47., 66., 20., 63.,  1.],
       [60., 17., 42., 87.,  1.],
       [88., 34., 97., 62.,  1.]])

### np.concatenate
     numpy.concatenate() function concatenate a sequence of arrays along an existing axis.

In [15]:
a=np.arange(6).reshape(2,3)
b=np.arange(6,12).reshape(2,3)

In [16]:
a

array([[0, 1, 2],
       [3, 4, 5]])

In [17]:
b

array([[ 6,  7,  8],
       [ 9, 10, 11]])

In [18]:
np.concatenate((a,b),axis=0) # Join in Row Wise

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [19]:
np.concatenate((a,b),axis=1) # Join in Column wise

array([[ 0,  1,  2,  6,  7,  8],
       [ 3,  4,  5,  9, 10, 11]])

### np.unique
     With the help of np.uinque() method, we can get the unique values from an array given as parameter in np.unique() 
     method.

In [20]:
e=np.array([1,1,1,2,3,4,5,1,3,3,4,4,6,5,3,4,5,1,1])
f=np.array([[1,2,1,1,2,3],[2,3,1,1,2,1]])

In [21]:
e

array([1, 1, 1, 2, 3, 4, 5, 1, 3, 3, 4, 4, 6, 5, 3, 4, 5, 1, 1])

In [22]:
f

array([[1, 2, 1, 1, 2, 3],
       [2, 3, 1, 1, 2, 1]])

In [23]:
np.unique(e) # It give Unique values of an array

array([1, 2, 3, 4, 5, 6])

In [24]:
np.unique(f)

array([1, 2, 3])

### np.expand_dims
     With the help of numpy.expand_dims() method, we can get the expanded dimensions of an array
     
     It use to create Row Vector / Column Vector.

In [25]:
a

array([[0, 1, 2],
       [3, 4, 5]])

In [26]:
np.expand_dims(a,axis=0)

array([[[0, 1, 2],
        [3, 4, 5]]])

In [27]:
np.expand_dims(a,axis=1)

array([[[0, 1, 2]],

       [[3, 4, 5]]])

### np.where
     The numpy.where() function returns the indices of elements in an input array where the given condition is satisfied.
     
     np.where( condition, True_Value, False_Value )

In [42]:
a

array([21, 26, 43, 76, 11, 58, 91,  9, 14, 96, 40, 83, 99, 76, 58])

In [43]:
# FIND ALL INDICES WITH VALUE GREATER THAN 50.

np.where(a>50)   # It gives the index number of Satisfy Condition

(array([ 3,  5,  6,  9, 11, 12, 13, 14], dtype=int64),)

In [44]:
a[np.where(a>50)]

array([76, 58, 91, 96, 83, 99, 76, 58])

In [45]:
# REPLACE ALL VALUES > 50 WITH 0

np.where(a>50,0,a)

array([21, 26, 43,  0, 11,  0,  0,  9, 14,  0, 40,  0,  0,  0,  0])

In [46]:
# REPLACE EVEN NUMBER WITH 0

np.where(a % 2 ==0,0,a) 

array([21,  0, 43,  0, 11,  0, 91,  9,  0,  0,  0, 83, 99,  0,  0])

### np.argmax
     The numpy.argmax() functions returns indices of the max element of the array in a particular axis.

In [47]:
a

array([21, 26, 43, 76, 11, 58, 91,  9, 14, 96, 40, 83, 99, 76, 58])

In [49]:
np.argmax(a)

12

In [50]:
a[np.argmax(a)]

99

In [48]:
b

array([[91,  5, 63, 96],
       [29, 16, 62, 20],
       [ 7, 89, 85, 67],
       [34, 19,  4, 82],
       [41, 25, 10, 71],
       [82, 76, 84, 86]])

In [54]:
np.argmax(b,axis=0)

array([0, 2, 2, 0], dtype=int64)

In [57]:
np.argmax(b,axis=1)

array([3, 2, 1, 3, 3, 3], dtype=int64)

### np.cumsum
     numpy.cumsum() function is used when we want to compute the cummulative sum of array elements over a given axis.

In [59]:
a

array([21, 26, 43, 76, 11, 58, 91,  9, 14, 96, 40, 83, 99, 76, 58])

In [60]:
np.cumsum(a)

array([ 21,  47,  90, 166, 177, 235, 326, 335, 349, 445, 485, 568, 667,
       743, 801])

In [61]:
b

array([[91,  5, 63, 96],
       [29, 16, 62, 20],
       [ 7, 89, 85, 67],
       [34, 19,  4, 82],
       [41, 25, 10, 71],
       [82, 76, 84, 86]])

In [62]:
np.cumsum(b) # First it Flatten the array to 1D array then do Cummulative Sum

array([  91,   96,  159,  255,  284,  300,  362,  382,  389,  478,  563,
        630,  664,  683,  687,  769,  810,  835,  845,  916,  998, 1074,
       1158, 1244])

In [63]:
np.cumsum(b,axis=0) # Column wise Cummulative sum

array([[ 91,   5,  63,  96],
       [120,  21, 125, 116],
       [127, 110, 210, 183],
       [161, 129, 214, 265],
       [202, 154, 224, 336],
       [284, 230, 308, 422]])

In [64]:
np.cumsum(b,axis=1) # Row wise Cummulative sum

array([[ 91,  96, 159, 255],
       [ 29,  45, 107, 127],
       [  7,  96, 181, 248],
       [ 34,  53,  57, 139],
       [ 41,  66,  76, 147],
       [ 82, 158, 242, 328]])

### np.percentile
     numpy.percentile() function used to compute the nth percentile of the given data (array elements) along the specified axis.

In [65]:
a

array([21, 26, 43, 76, 11, 58, 91,  9, 14, 96, 40, 83, 99, 76, 58])

In [66]:
np.percentile(a,90)

94.0

In [67]:
np.percentile(a,0)

9.0

In [68]:
np.percentile(a,50)

58.0

### np.histogram
     Numpy has a built-in-numpy.histogram() function which represents the frequency of data distribution in the graphical form


In [69]:
a

array([21, 26, 43, 76, 11, 58, 91,  9, 14, 96, 40, 83, 99, 76, 58])

In [70]:
np.histogram(a,10)

(array([3, 2, 0, 2, 0, 2, 0, 2, 1, 3], dtype=int64),
 array([ 9., 18., 27., 36., 45., 54., 63., 72., 81., 90., 99.]))

In [71]:
np.histogram(a,bins=[0,10,20,30,40,50,60,70,80,90,100])

(array([1, 2, 2, 0, 2, 2, 0, 2, 1, 3], dtype=int64),
 array([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100]))

In [72]:
np.histogram(a,bins=[0,10,20,30,40,50,60,70,80,90,100],range=True)

(array([1, 2, 2, 0, 2, 2, 0, 2, 1, 3], dtype=int64),
 array([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100]))

In [73]:
np.histogram(a,bins=[0,10,20,30,40,50,60,70,80,90,100],density=True)

(array([0.00666667, 0.01333333, 0.01333333, 0.        , 0.01333333,
        0.01333333, 0.        , 0.01333333, 0.00666667, 0.02      ]),
 array([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100]))

### np.corrcoef
     Return Pearson product-- moment correlation coefficients

In [74]:
salary=np.array([20000,40000,25000,35000,60000])
experience=np.array([1,2,3,4,5])

In [75]:
np.corrcoef(salary,experience)

array([[1.        , 0.76150962],
       [0.76150962, 1.        ]])

### np.isin
     With the help of numpy.isin() method,we can see that one array having values are checked in a different numpy array having different elements with different sizes.

In [76]:
a

array([21, 26, 43, 76, 11, 58, 91,  9, 14, 96, 40, 83, 99, 76, 58])

In [78]:
items=[10,20,30,40,90,100]

In [79]:
np.isin(a,items)

array([False, False, False, False, False, False, False, False, False,
       False,  True, False, False, False, False])

In [80]:
a[np.isin(a,items)]

array([40])

### np.flip
     The numpy.flip() function reverses the order of array elements along the specified axis, preserving the shape of the array.

In [81]:
a

array([21, 26, 43, 76, 11, 58, 91,  9, 14, 96, 40, 83, 99, 76, 58])

In [82]:
np.flip(a) 

array([58, 76, 99, 83, 40, 96, 14,  9, 91, 58, 11, 76, 43, 26, 21])

In [83]:
b

array([[91,  5, 63, 96],
       [29, 16, 62, 20],
       [ 7, 89, 85, 67],
       [34, 19,  4, 82],
       [41, 25, 10, 71],
       [82, 76, 84, 86]])

In [88]:
np.flip(b) # Row+Column wise flipping

array([[86, 84, 76, 82],
       [71, 10, 25, 41],
       [82,  4, 19, 34],
       [67, 85, 89,  7],
       [20, 62, 16, 29],
       [96, 63,  5, 91]])

In [86]:
np.flip(b,axis=0) # Column wise Flipping

array([[82, 76, 84, 86],
       [41, 25, 10, 71],
       [34, 19,  4, 82],
       [ 7, 89, 85, 67],
       [29, 16, 62, 20],
       [91,  5, 63, 96]])

In [87]:
np.flip(b,axis=1) # Row wise Flipping

array([[96, 63,  5, 91],
       [20, 62, 16, 29],
       [67, 85, 89,  7],
       [82,  4, 19, 34],
       [71, 10, 25, 41],
       [86, 84, 76, 82]])

### np.put
     The numpy.put() function replaces specific elements of an array with given values p_array. Array indexed works on flattened away.

In [89]:
a

array([21, 26, 43, 76, 11, 58, 91,  9, 14, 96, 40, 83, 99, 76, 58])

In [90]:
# It has 3 arguments--> Array, Indexes, Values.

np.put(a,[0,2],[210,430]) 

# It make permanent changes, so output will not show.

In [91]:
a

array([210,  26, 430,  76,  11,  58,  91,   9,  14,  96,  40,  83,  99,
        76,  58])

### np.delete
     The numpy.delete() function returns a new array with the deletion of sub-arrays along with the mentioned axis.

In [92]:
a

array([210,  26, 430,  76,  11,  58,  91,   9,  14,  96,  40,  83,  99,
        76,  58])

In [93]:
np.delete(a,0) # It has two arguments--> Array, Indexes

array([ 26, 430,  76,  11,  58,  91,   9,  14,  96,  40,  83,  99,  76,
        58])

In [95]:
np.delete(a,[0,2])

array([26, 76, 11, 58, 91,  9, 14, 96, 40, 83, 99, 76, 58])

### np.clip
     numpy.clip() function is used to clip(limit) the values in an array.

In [96]:
a

array([210,  26, 430,  76,  11,  58,  91,   9,  14,  96,  40,  83,  99,
        76,  58])

In [98]:
np.clip(a,a_min=10,a_max=30) # It has 3 arguments--> Array, Array_min_Value, Array_max_Value

# If the Array cross the Min_Value & Max_Value then the crossing values are replaced by Min_Value & Max_Value 

array([30, 26, 30, 30, 11, 30, 30, 10, 14, 30, 30, 30, 30, 30, 30])