In [ ]:
# ! pip install numpy

In [1]:
import numpy as np

### 1D Array

In [4]:
a=np.array([1,10]) # Arrya is used for convert the list to Numpy_Array

In [5]:
a

array([ 1, 10])

In [6]:
print(a)

[ 1 10]


In [7]:
type(a) # Show the Array type

numpy.ndarray

In [9]:
a.shape # Show the Shape of the Array

(2,)

In [10]:
a.ndim # Show the Dimension of the Array

1

In [11]:
a.size # Show the size of the Array

2

In [12]:
a.itemsize # Show the item Size of Memory

4

In [13]:
a.dtype # Show the Data Type

dtype('int32')

### 2D Array

In [14]:
b=np.array([[2,3,4,5],[10,7,8,9]])

In [15]:
b

array([[ 2,  3,  4,  5],
       [10,  7,  8,  9]])

In [16]:
b.shape # Show the shape of the Array. 2 Means Rows,4 Means Columns 

(2, 4)

In [17]:
b.size

8

In [18]:
b.itemsize

4

In [19]:
b.dtype

dtype('int32')

In [20]:
b.ndim

2

### ONE's FUNCTION

In [22]:
np.ones((2,4)) # it store the Shape in tuple form

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [23]:
c=np.ones((3,4),dtype="int64")

In [24]:
c

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]], dtype=int64)

In [25]:
c.ndim

2

In [26]:
c.shape

(3, 4)

In [27]:
c.size

12

In [28]:
c.dtype

dtype('int64')

In [29]:
c.itemsize

8

### ZERO's Function

In [34]:
np.zeros((3,4)) # it store the shape in Tuple form

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

### DIAGANAL ARRAY

In [32]:
np.eye(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [33]:
np.eye(6,8)

array([[1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0.]])

In [43]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### ARANGE

In [35]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [36]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [37]:
np.arange(10,1,-1)

array([10,  9,  8,  7,  6,  5,  4,  3,  2])

In [38]:
np.arange(1,10,-1)

array([], dtype=int32)

### LINSPACE
    LINSPACE---> LINEAR SPACE

In [39]:
np.linspace(1,10)

array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
        1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
        2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
        3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
        4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
        5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
        6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
        7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
        8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
        9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ])

In [40]:
np.linspace(1,3,retstep=True)

(array([1.        , 1.04081633, 1.08163265, 1.12244898, 1.16326531,
        1.20408163, 1.24489796, 1.28571429, 1.32653061, 1.36734694,
        1.40816327, 1.44897959, 1.48979592, 1.53061224, 1.57142857,
        1.6122449 , 1.65306122, 1.69387755, 1.73469388, 1.7755102 ,
        1.81632653, 1.85714286, 1.89795918, 1.93877551, 1.97959184,
        2.02040816, 2.06122449, 2.10204082, 2.14285714, 2.18367347,
        2.2244898 , 2.26530612, 2.30612245, 2.34693878, 2.3877551 ,
        2.42857143, 2.46938776, 2.51020408, 2.55102041, 2.59183673,
        2.63265306, 2.67346939, 2.71428571, 2.75510204, 2.79591837,
        2.83673469, 2.87755102, 2.91836735, 2.95918367, 3.        ]),
 0.04081632653061224)

In [41]:
np.linspace(1,3)

array([1.        , 1.04081633, 1.08163265, 1.12244898, 1.16326531,
       1.20408163, 1.24489796, 1.28571429, 1.32653061, 1.36734694,
       1.40816327, 1.44897959, 1.48979592, 1.53061224, 1.57142857,
       1.6122449 , 1.65306122, 1.69387755, 1.73469388, 1.7755102 ,
       1.81632653, 1.85714286, 1.89795918, 1.93877551, 1.97959184,
       2.02040816, 2.06122449, 2.10204082, 2.14285714, 2.18367347,
       2.2244898 , 2.26530612, 2.30612245, 2.34693878, 2.3877551 ,
       2.42857143, 2.46938776, 2.51020408, 2.55102041, 2.59183673,
       2.63265306, 2.67346939, 2.71428571, 2.75510204, 2.79591837,
       2.83673469, 2.87755102, 2.91836735, 2.95918367, 3.        ])

In [42]:
np.linspace(1,3,endpoint=False)

array([1.  , 1.04, 1.08, 1.12, 1.16, 1.2 , 1.24, 1.28, 1.32, 1.36, 1.4 ,
       1.44, 1.48, 1.52, 1.56, 1.6 , 1.64, 1.68, 1.72, 1.76, 1.8 , 1.84,
       1.88, 1.92, 1.96, 2.  , 2.04, 2.08, 2.12, 2.16, 2.2 , 2.24, 2.28,
       2.32, 2.36, 2.4 , 2.44, 2.48, 2.52, 2.56, 2.6 , 2.64, 2.68, 2.72,
       2.76, 2.8 , 2.84, 2.88, 2.92, 2.96])

### MIN,MAX,PRODUCT,SUM FUNCTIONS

In [46]:
a

array([ 1, 10])

In [47]:
np.min(a)

1

In [48]:
np.max(a)

10

In [49]:
np.sum(a)

11

In [50]:
np.prod(a)

10

In [51]:
b

array([[ 2,  3,  4,  5],
       [10,  7,  8,  9]])

#### IF YOU WANT THE COLUMN WISE / ROW WISE MAX,MIN,SUM,PRODUCT--->

In [52]:
b

array([[ 2,  3,  4,  5],
       [10,  7,  8,  9]])

__```0 ----> COLUMN
 1----> ROW 
```__

In [53]:
np.min(b,axis=0)

array([2, 3, 4, 5])

In [55]:
np.max(b,axis=0)

array([10,  7,  8,  9])

In [59]:
np.max(b,axis=1)

array([ 5, 10])

In [56]:
np.sum(b,axis=0)

array([12, 10, 12, 14])

In [58]:
np.sum(b,axis=1)

array([14, 34])

### MEAN,MEDIAN,STD,VAR Function

In [60]:
np.mean(b)

6.0

In [61]:
np.median(b)

6.0

In [62]:
np.std(b)

2.7386127875258306

In [63]:
np.var(b)

7.5

### DOT PRODUCT

In [66]:
b # (2,4)

array([[ 2,  3,  4,  5],
       [10,  7,  8,  9]])

In [68]:
c=np.reshape(b,(4,2))

In [69]:
c # (4,2)

array([[ 2,  3],
       [ 4,  5],
       [10,  7],
       [ 8,  9]])

In [70]:
np.dot(b,c) # (2,2)

array([[ 96,  94],
       [200, 202]])

### LOG, EXPONENT FUNCTION

In [77]:
f=np.log(b)

In [78]:
f

array([[0.69314718, 1.09861229, 1.38629436, 1.60943791],
       [2.30258509, 1.94591015, 2.07944154, 2.19722458]])

In [74]:
e=np.exp(b)

In [75]:
e

array([[7.38905610e+00, 2.00855369e+01, 5.45981500e+01, 1.48413159e+02],
       [2.20264658e+04, 1.09663316e+03, 2.98095799e+03, 8.10308393e+03]])

### ROUND,FLOOR,CEIL

In [79]:
np.round(f) # It round the decimal number

array([[1., 1., 1., 2.],
       [2., 2., 2., 2.]])

In [80]:
np.floor(f) # It give the numbers without decimal number

array([[0., 1., 1., 1.],
       [2., 1., 2., 2.]])

In [81]:
np.ceil(f) 

array([[1., 2., 2., 2.],
       [3., 2., 3., 3.]])

### 

### 

### INDEXING & SLICING

In [82]:
a1=np.arange(10)
b1=np.arange(12).reshape(3,4)
c1=np.arange(8).reshape(2,2,2)

In [84]:
print(a1)
print()
print(b1)
print()
print(c1)

[0 1 2 3 4 5 6 7 8 9]

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


In [85]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## INDEXING

### 1D Array Indexing
    It similar as List Indexing

In [86]:
a1[-1]

9

In [87]:
a1[0]

0

In [88]:
a1[5]

5

### 2D Array Indexing
    [ROW,COLUMN]

In [89]:
b1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [90]:
b1[1,2]

6

In [92]:
b1[2,1]

9

### 3D Array Indexing
    [BLOCK,ROW,COLUMN]

In [93]:
c1

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [94]:
c1[1,0,1]

5

In [95]:
c1[0,1,1]

3

In [96]:
c1[0,0,0]

0

In [97]:
c1[1,1,0]

6

## SLICING

### 1D ARRAY
    It similar to List

In [98]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [99]:
a1[2:5]

array([2, 3, 4])

### 2D ARRAY
    [ROW,COLUMN]

In [100]:
b1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [102]:
b1[0,:] # It gives the all elements of 1st Row

array([0, 1, 2, 3])

In [103]:
b1[:,2] # It give the all elements of 3rd Column

array([ 2,  6, 10])

In [104]:
b1[1:,1:3] # It gives the Particular elements that is (5,6,9,10)

array([[ 5,  6],
       [ 9, 10]])

In [105]:
b1[0::2,0::3] # It gives the Particular elements that is (0,3,8,11)

array([[ 0,  3],
       [ 8, 11]])

In [106]:
b1[::2,::3] # It gives the Particular elements that is (0,3,8,11)

array([[ 0,  3],
       [ 8, 11]])

In [107]:
b1[::2,1::2] # It gives the Particular elements that is (1,3,9,11)

array([[ 1,  3],
       [ 9, 11]])

In [111]:
b1[1,::3] # It gives the Particular elements that is (4,7)

array([4, 7])

In [112]:
b1[0:2,1:] # It gives the Particular elements that is (1,2,3,5,6,7)

array([[1, 2, 3],
       [5, 6, 7]])

### 3D ARRAY
    [BLOCK,ROW,COLUMN]

In [113]:
d1=np.arange(27).reshape(3,3,3)

In [114]:
d1

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [115]:
d1[1] # It given 2nd Block 

array([[ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [116]:
d1[::2] # It give 1st & 3rd Block

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [119]:
d1[0,1,:] # It give the 1st block of 2nd Row Elements

array([3, 4, 5])

In [120]:
d1[0,1] # It give the 1st block of 2nd Row Elements

array([3, 4, 5])

In [121]:
d1[1,:,1] # It gives the 2nd Block of 2nd Column Elements

array([10, 13, 16])

In [123]:
d1[2,1:,1:] # It gives the 3rd Block of elements that is (22,23,25,26)

array([[22, 23],
       [25, 26]])

In [128]:
d1[0::2,0,0::2] # 1st Block of Elements (0,2) & 3rd Block of Elements (18,20)

array([[ 0,  2],
       [18, 20]])

### ITERATING

In [138]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [134]:
for i in a1:
    print(i)

0
1
2
3
4
5
6
7
8
9


In [137]:
b1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [136]:
for j in b1:
    print(j)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [133]:
c1

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [139]:
for k in c1:
    print(k)

[[0 1]
 [2 3]]
[[4 5]
 [6 7]]


In [140]:
for k1 in np.nditer(c1): # It give the all elements
    print(k1)

0
1
2
3
4
5
6
7


### RESHAPING

#### RESHAPE

In [141]:
b1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [147]:
b3=np.reshape(b1,(4,3)) 

In [148]:
b3

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

#### TRANSPOSE

In [146]:
np.transpose(b1)

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [149]:
b3.T

array([[ 0,  3,  6,  9],
       [ 1,  4,  7, 10],
       [ 2,  5,  8, 11]])

#### RAVEL

In [150]:
b1.ravel() # It will give 1D Array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [151]:
c1.ravel()

array([0, 1, 2, 3, 4, 5, 6, 7])

### STACKING
    STACKING--->JOIN
    IF THE SHAPE OF TWO ARRAY ARE SAME, THEN YOU WILL USE STACKING

In [152]:
d2=np.arange(12).reshape(3,4)
d3=np.arange(12,24).reshape(3,4)

In [153]:
d2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [154]:
d3

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

#### HORIZONTAL

In [156]:
np.hstack((d2,d3))  # (ROW=3,COLUMN=6)    # Write the Shape in Tuple.

array([[ 0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23]])

#### VERTICAL

In [157]:
np.vstack((d2,d3)) # (ROW=6,COLUMN=3)  # Write the Shape in Tuple

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

### SPLITTING
    OPPOSITE OF STACKING
    YOU WILL GIVE WRITE SPLITING VALUE.

In [161]:
d2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

#### HORIZONTAL

In [160]:
np.hsplit(d2,2)

[array([[0, 1],
        [4, 5],
        [8, 9]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11]])]

#### VERTICAL

In [168]:
np.vsplit(d2,3)

[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]])]

## CREATING ARRAY USING RANDOM

### RANDOM.RAND

In [169]:
np.random.rand(3,4) # It only take Shape of the Array & give Positive Decimal Numbers

array([[0.02023485, 0.50803202, 0.32783303, 0.10253285],
       [0.93575078, 0.29817274, 0.46385822, 0.22579939],
       [0.74412068, 0.66203227, 0.82553644, 0.13989135]])

### RANDOM.RANDN

In [170]:
np.random.randn(5,7) # It take Shape of the Array & give Positive as well as Negative Decimal Numbers

array([[ 0.17464305,  0.53906835,  1.09680322,  0.17551857, -0.55666905,
        -0.42207969,  0.44984569],
       [ 0.73633884, -0.44403746, -0.307843  ,  0.94243447,  0.5772415 ,
         0.36352411,  0.52859716],
       [-0.16165186, -0.58631106, -0.10268964,  1.54385287, -0.14953647,
        -1.77937509,  2.41872427],
       [-0.57214609, -0.81863917, -2.21553153, -1.54597422,  0.18388684,
        -0.30936293, -0.86664191],
       [-0.24725446,  1.27160518, -1.86308046,  0.34224151, -1.74580613,
         1.84333714,  0.72275479]])

### RANDOM.RANDINT

In [174]:
np.random.randint(1,5,(2,4)) # It take Starting Value, Ending Value & Shape of Array

array([[4, 3, 1, 2],
       [1, 3, 4, 1]])

### RANDOM.CHOICE

In [177]:
n1=np.arange(2,6)

In [178]:
n1

array([2, 3, 4, 5])

In [180]:
# It take Array Variable, New Array Shape, Probabilities of the Given Array inside the List.

# The Sum of all the Probabilities is equal to 1.

np.random.choice(n1,(3,5),p=[0.1,0.0,0.2,0.7]) 

array([[5, 5, 5, 4, 5],
       [2, 4, 5, 5, 5],
       [5, 5, 5, 5, 5]])

In [185]:
np.random.choice(n1,4,replace=False) # You only give small size that is in 1D Array

array([2, 5, 4, 3])

In [187]:
np.random.choice(n1,4,replace=False,p=[0.1,0.1,0.1,0.7]) # You can not take 0.0 in p.

array([3, 5, 2, 4])